# Part 1 — Inspect & Understand the Dataset

In [38]:
#Q1. Load the dataset
import pandas as pd
df = pd.read_csv("C:/Users/anilr/Downloads/customer_analytics - customer_analytics.csv")

#Load messy_customer_analytics_2000x15.csv into a DataFrame called df.
#Then display the first 10 rows.
df.head(10)
#Use: pd.read_csv(), head()

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
5,101334,68,37087,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 00:00:00,Yes,Low,15121.16,6,8.5
6,100415,47,67229,99629.81,464,4,Chennai,Retail,Online,2024-01-16 00:00:00,Yes,High,17655.61,31,2.8
7,100983,65,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 00:00:00,Yes,Medium,1720.85,139,9.7
8,100417,63,153267,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 00:00:00,Yes,High,38043.07,76,7.1
9,101472,42,missing,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 00:00:00,Yes,Medium,11472.36,124,9.1

In [39]:
#Q2. Inspect the end of the dataset
#Display the last 15 rows.
#Use: tail()
df.tail(15)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
2025,100088,51,214004,173779.91,686,6,Pune,Premium,Branch,2022-04-22 00:00:00,Yes,Medium,39764.87,85,4.9
2026,101483,not_available,117573,261905.82,657,2,Pune,NaN,Branch,2022-07-02 00:00:00,Yes,Medium,39559.16,7,1.9
2027,100331,54,123511,280896.35,388,5,Pune,Premium,Mobile,2024-09-11 00:00:00,No,High,NaN,48,6.7
2028,101239,31,125500,189174.28,846,11,Delhi,Corporate,Agent,2022-04-08 00:00:00,Yes,Low,22161.09,102,8.5
2029,100467,NaN,101619,279182.04,392,3,Bangalore,Retail,Mobile,2023-07-26 00:00:00,Yes,High,37316.48,100,7.3
2030,100122,41,201611,40736.71,507,15,Bangalore,SME,Agent,2024-11-03 00:00:00,Yes,High,18815.18,58,7.2
2031,101639,61,128850,266135.8,840,9,Kolkata,SME,Mobile,2026-01-15 00:00:00,Yes,Low,34300.44,83,5.0
2032,101045,33,88037,129948.93,449,8,Mumbai,Premium,Mobile,2022-11-30 00:00:00,Yes,High,not_available,147,9.7
2033,101725,43,122756,36633.45,487,8,Pune,NaN,Mobile,2021-07-04 00:00:00,No,High,10165.71,14,6.4
2034,101096,18,189232,235131.72,306,10,hyderabad,SME,Mobile,2025-09-10 00:00:00,No,High,27227.44,85,5.9
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [40]:
#Q3. Random inspection
#Display 10 random records.
#Use: sample()
df.sample(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
1037,101362,19,93099,13635.75,369,0,NaN,NaN,Mobile,2022-07-24 00:00:00,Yes,High,16640.49,57,2.5
345,101678,23,241192,18565.71,unknown,1,mumbai,Premium,Agent,2024-03-05 00:00:00,Yes,Low,41662.69,47,4.1
639,101076,51,35749,83537.26,545,1,Kolkata,Corporate,Online,2024-04-28 00:00:00,Yes,High,24918.36,124,6.1
1287,100815,45,141492,68751.59,828,8,Hyderabad,Premium,Branch,2025-06-30 00:00:00,Yes,Low,30268.12,78,6.3
954,101640,52,188730,125954.61,690,12,Kolkata,Retail,Online,2025-07-06 00:00:00,Yes,Medium,38337.76,139,1.4
11,101576,25,93673,65086.87,477,13,Bangalore,Premium,Online,2025-11-22 00:00:00,Yes,High,24777.75,56,8.1
1395,101845,missing,225857,251178.9,582,12,Delhi,Corporate,Branch,2022-03-21 00:00:00,Yes,Medium,36099.01,131,2.1
1187,101490,69,98997,76181.33,499,10,Bangalore,Retail,Branch,2024-04-17 00:00:00,Yes,High,13976.25,87,2.3
395,101839,46,37109,97747.04,736,8,Bangalore,Corporate,Branch,NaN,Yes,Low,NaN,47,3.4
806,100661,68,214420,36609.15,797,7,Kolkata,Corporate,Branch,2021-08-11 00:00:00,Yes,Low,48398.53,56,6.5

In [41]:
#Q4. Dataset audit
#Use info() to identify:
df.info()
#• Number of rows = 2040
#• Number of columns = 12
#• Columns with missing values = 14
#• Columns having incorrect/object datatypes = float64(1), int64(2), object(12)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB

In [42]:
#Q5. Missing-value audit
#Calculate the number of missing values in every column.
df.isnull().sum()
#Then verify the result using both:
#isnull() and isna()
df.isna().sum()

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

# Part 2 — Detect & Fix Data Quality Problems

In [43]:
#Q6. Duplicate investigation
#Find how many duplicate rows exist.
df.duplicated().sum()
#Do not remove them yet.
#Use: duplicated()

np.int64(40)

In [44]:
#Q7. Remove duplicates
#Remove all duplicate records and store the cleaned result back into df.
df.drop_duplicates(inplace = True)


#Then verify that duplicates no longer exist.
df.duplicated().sum()

#Use: drop_duplicates(), duplicated()

np.int64(0)

In [45]:
#Q8. Numeric column investigation
#Select only numeric columns.

df.select_dtypes(int).sum()
df.select_dtypes(float).sum()


#Identify which columns are currently numeric and which potentially numeric columns have become object because of invalid values.
#Use: select_dtypes()

Satisfaction_Score    10762.4
dtype: float64

In [46]:
#Q9. Fix Age
#The Age column contains:
#• Valid numbers
#• Missing values
#• Invalid text such as unknown, N/A, etc.
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
#Convert Age into a proper numeric column.
#Invalid values should become missing values.
#Then fill missing Age values using the median age.
median_age = df["Age"].median()
df["Age"] = df["Age"].fillna(median_age)

print(df["Age"])
print(df["Age"].dtype)
df
#Use: pd.to_numeric(), median(), fillna()

0       55.0
1       32.0
2       23.0
3       66.0
4       67.0
        ...
2035    42.0
2036    31.0
2037    25.0
2038    64.0
2039    55.0
Name: Age, Length: 2000, dtype: float64
float64

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23.0,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66.0,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67.0,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55.0,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [47]:
#Q10. Fix Annual Income
#Clean Annual_Income.
#Requirements:
#1. Convert invalid values to missing.
df.isnull().sum()
#2. Convert the column to a numeric datatype.
df['Annual_Income'] = pd.to_numeric(df['Annual_Income'],errors="coerce")

#3. Calculate the median.
df['Annual_Income_median'] = df['Annual_Income'].median()
df['Annual_Income_median']

#4. Fill missing values using the median.
df['Annual_Income_median'] = df['Annual_Income'].fillna("Annual_Income_median")
print(df['Annual_Income_median'])
df
#Use: pd.to_numeric(), median(), fillna(), astype()

0        44033.0
1       215546.0
2       226403.0
3        87824.0
4        31570.0
          ...
2035     88530.0
2036    205738.0
2037    211994.0
2038     30105.0
2039    248332.0
Name: Annual_Income_median, Length: 2000, dtype: object

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,Annual_Income_median
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1,44033.0
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2,215546.0
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3,226403.0
3,101968,66.0,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7,87824.0
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7,31570.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6,88530.0
2036,101295,31.0,205738.0,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6,205738.0
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3,211994.0
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3,30105.0
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1,248332.0

# Part 3 — Numerical Cleaning

In [48]:
#Q11. Clean Account Balance
#The Account_Balance column contains invalid strings and missing values.
#Clean the column and replace missing values with the mean Account Balance.
#Use:
#• pd.to_numeric()
df['Account_Balance'] = pd.to_numeric(df['Account_Balance'],errors="coerce")
#• mean()
Account_Balance_mean = df['Account_Balance'].mean()
Account_Balance_mean

#• fillna()
df['Account_Balance'] = df['Account_Balance'].fillna(Account_Balance_mean)
print(df['Account_Balance'])
df

0       111350.85
1       254378.37
2       159975.42
3       295741.60
4       242423.78
          ...
2035    153490.72
2036    270989.40
2037    160507.65
2038     32117.15
2039    274980.99
Name: Account_Balance, Length: 2000, dtype: float64

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,Annual_Income_median
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1,44033.0
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2,215546.0
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3,226403.0
3,101968,66.0,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7,87824.0
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7,31570.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6,88530.0
2036,101295,31.0,205738.0,270989.40,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6,205738.0
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3,211994.0
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3,30105.0
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1,248332.0

In [49]:
#Q12. Clean Credit Score
#Clean Credit_Score.
df['Credit_Score'] = pd.to_numeric(df['Credit_Score'],errors="coerce")
df
#Invalid values should become missing.
df.isnull()
#Then replace missing values with the median Credit Score.
Credit_Score_median = df['Credit_Score'].median()
Credit_Score_median
df['Credit_Score'] = df['Credit_Score'].fillna(Credit_Score_median)
df['Credit_Score']
#Finally convert the column to integer.
df['Credit_Score'] = df['Credit_Score'].astype('int')
print(df['Credit_Score'])
df
#Use:
#• pd.to_numeric()
#• median()
#• fillna()
#• astype()

0       772
1       374
2       668
3       315
4       370
       ...
2035    677
2036    392
2037    737
2038    794
2039    783
Name: Credit_Score, Length: 2000, dtype: int64

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,Annual_Income_median
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1,44033.0
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2,215546.0
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3,226403.0
3,101968,66.0,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7,87824.0
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7,31570.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6,88530.0
2036,101295,31.0,205738.0,270989.40,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6,205738.0
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3,211994.0
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3,30105.0
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1,248332.0

In [50]:
#Q13. Clean Monthly Spend
#Clean Monthly_Spend.
#Then:
#• Convert it to numeric.
df['Monthly_Spend'] = pd.to_numeric(df['Monthly_Spend'],errors="coerce")

#• Replace invalid values.
df.ffill(inplace=True)
#• Replace missing values using the median.
Monthly_Spendmedian = df['Monthly_Spend'].median()
print(Monthly_Spendmedian)
df
#• Make sure the final column is numeric.
df1 = df["Monthly_Spend"].astype(int)
print(df1)
df

24682.72
0       23066
1       23066
2       28536
3       12869
4       34163
        ...
2035     8455
2036    34087
2037    26518
2038    20943
2039    48511
Name: Monthly_Spend, Length: 2000, dtype: int64

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,Annual_Income_median
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1,44033.0
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,23066.19,106,8.2,215546.0
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3,226403.0
3,101968,66.0,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7,87824.0
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7,31570.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6,88530.0
2036,101295,31.0,205738.0,270989.40,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6,205738.0
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3,211994.0
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3,30105.0
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,2023-08-26 00:00:00,Yes,Low,48511.32,119,3.1,248332.0

In [51]:
#Q14. Clean Transactions
df['Transactions'] = pd.to_numeric(df['Transactions'],errors="coerce")
#The Transactions column contains invalid strings.
df.ffill(inplace=True)
#Convert it to numeric and replace invalid values with the median number of transactions.
Transactions_median = df['Transactions'].median()
print(Transactions_median)
#Then convert the final column to integer.
df1 = df["Transactions"].astype(int)
print(df1)
df

76.0
0       135
1       106
2       146
3       115
4        94
       ...
2035    119
2036    134
2037     87
2038    107
2039    119
Name: Transactions, Length: 2000, dtype: int64

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,Annual_Income_median
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135.0,3.1,44033.0
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,23066.19,106.0,8.2,215546.0
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146.0,6.3,226403.0
3,101968,66.0,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115.0,9.7,87824.0
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94.0,3.7,31570.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119.0,8.6,88530.0
2036,101295,31.0,205738.0,270989.40,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134.0,2.6,205738.0
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87.0,1.3,211994.0
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107.0,9.3,30105.0
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,2023-08-26 00:00:00,Yes,Low,48511.32,119.0,3.1,248332.0

In [52]:
#Q15. Clean Satisfaction Score
#Clean Satisfaction_Score.
df['Satisfaction_Score'] = pd.to_numeric(df['Satisfaction_Score'],errors="coerce")
#Replace missing/invalid values using the mean Satisfaction Score.
Satisfaction_Score_median = df['Satisfaction_Score'].median()
print(Satisfaction_Score_median)
#Then convert the column to float.
df1 = df["Satisfaction_Score"].astype(int)
print(df1)
df

5.7
0       3
1       8
2       6
3       9
4       3
       ..
2035    8
2036    2
2037    1
2038    9
2039    3
Name: Satisfaction_Score, Length: 2000, dtype: int64

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,Annual_Income_median
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135.0,3.1,44033.0
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,23066.19,106.0,8.2,215546.0
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146.0,6.3,226403.0
3,101968,66.0,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115.0,9.7,87824.0
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94.0,3.7,31570.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119.0,8.6,88530.0
2036,101295,31.0,205738.0,270989.40,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134.0,2.6,205738.0
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87.0,1.3,211994.0
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107.0,9.3,30105.0
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,2023-08-26 00:00:00,Yes,Low,48511.32,119.0,3.1,248332.0

# Part 4 — Date Cleaning

In [53]:
# Q16. Investigate Join_Date
#Inspect the Join_Date column.
#Identify the problems caused by:
#• Missing dates
#• Different date formats
#• Invalid date strings
# Do not clean it yet.
# Q16. Investigate Join_Date

print(df["Join_Date"].head(20))


df["Join_Date"].dtype

df["Join_Date"].isna().sum()

df["Join_Date"].unique()
df["Join_Date"].nunique()
df

0     2022-08-15 00:00:00
1     2025-01-11 00:00:00
2     2024-08-01 00:00:00
3     2021-05-15 00:00:00
4     2026-02-03 00:00:00
5     2023-06-04 00:00:00
6     2024-01-16 00:00:00
7     2024-06-26 00:00:00
8     2025-03-12 00:00:00
9     2021-10-07 00:00:00
10    2023-03-02 00:00:00
11    2025-11-22 00:00:00
12    2021-06-25 00:00:00
13    2025-11-19 00:00:00
14    2025-08-26 00:00:00
15    2024-05-05 00:00:00
16    2022-01-07 00:00:00
17    2022-05-25 00:00:00
18    2022-10-07 00:00:00
19    2023-08-10 00:00:00
Name: Join_Date, dtype: object

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,Annual_Income_median
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135.0,3.1,44033.0
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,23066.19,106.0,8.2,215546.0
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146.0,6.3,226403.0
3,101968,66.0,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115.0,9.7,87824.0
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94.0,3.7,31570.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119.0,8.6,88530.0
2036,101295,31.0,205738.0,270989.40,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134.0,2.6,205738.0
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87.0,1.3,211994.0
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107.0,9.3,30105.0
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,2023-08-26 00:00:00,Yes,Low,48511.32,119.0,3.1,248332.0

In [54]:
'''Q17. Convert Join_Date
Convert Join_Date into a proper Pandas datetime column.
Any invalid dates should become missing values.
Use: pd.to_datetime()

'''
df["Join_Date"] = pd.to_datetime(df["Join_Date"], errors="coerce")


df["Join_Date"].head()

df["Join_Date"].dtype
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,Annual_Income_median
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066.19,135.0,3.1,44033.0
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11,Yes,High,23066.19,106.0,8.2,215546.0
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01,No,Medium,28536.34,146.0,6.3,226403.0
3,101968,66.0,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869.71,115.0,9.7,87824.0
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03,No,High,34163.02,94.0,3.7,31570.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10,No,Medium,8455.42,119.0,8.6,88530.0
2036,101295,31.0,205738.0,270989.40,392,8,Mumbai,Corporate,Agent,2025-07-05,Yes,High,34087.69,134.0,2.6,205738.0
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17,Yes,Low,26518.74,87.0,1.3,211994.0
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26,No,Low,20943.11,107.0,9.3,30105.0
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,2023-08-26,Yes,Low,48511.32,119.0,3.1,248332.0

In [55]:
'''Q18. Handle missing dates
After conversion, find how many missing dates remain.
Then replace missing dates appropriately using a reasonable date-based strategy.'''

df["Join_Date"].isna().sum()

median_date = df["Join_Date"].median()

df["Join_Date"] = df["Join_Date"].fillna(median_date)
df["Join_Date"].isna().sum()

df["Join_Date"].head(10)

0   2022-08-15
1   2025-01-11
2   2024-08-01
3   2021-05-15
4   2026-02-03
5   2023-06-04
6   2024-01-16
7   2024-06-26
8   2025-03-12
9   2021-10-07
Name: Join_Date, dtype: datetime64[ns]

# Part 5 — Categorical Cleaning

In [56]:
'''Q19. Clean City
The City column contains values such as:
Mumbai
mumbai
Mumbai
mumbai
Standardize the values so that logically identical cities are represented consistently.
Then check the unique frequency distribution.
Use: replace(), value_counts()'''

df["City"] = df["City"].replace({
    "mumbai": "Mumbai",
    "MUMBAI": "Mumbai"
})

df["City"].value_counts()

City
Mumbai       323
Hyderabad    288
Delhi        280
Kolkata      273
Pune         260
Chennai      239
Bangalore    238
hyderabad     21
bangalore     17
pune          17
delhi         17
kolkata       15
chennai       12
Name: count, dtype: int64

In [57]:
'''Q20. Analyze Segment
Check the frequency of:
Retail
SME
Corporate
Premium
Also determine whether missing values exist.
Then replace missing Segment values with the most appropriate category based on your
analysis.
Use: value_counts(), fillna()'''

df["Segment"].value_counts()

df["Segment"].isna().sum()

most_frequent_segment = df["Segment"].mode()[0]
most_frequent_segment

df["Segment"] = df["Segment"].fillna(most_frequent_segment)


df["Segment"].isna().sum()
df["Segment"].value_counts()

Segment
Premium      544
Retail       495
Corporate    489
SME          472
Name: count, dtype: int64

In [58]:
'''Q21. Clean Active
Active is supposed to be a binary column, but it contains:
Yes
No
Y
N
YES
NO
yes
no
1
0
Transform these into a consistent representation:
Yes
No
Then verify the result with value_counts().
Use: replace(), value_counts()'''

df["Active"] = df["Active"].replace({
    "Y": "Yes",
    "N": "No",
    "YES": "Yes",
    "NO": "No",
    "yes": "Yes",
    "no": "No",
    1: "Yes",
    0: "No"
})


df["Active"].value_counts()
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,Annual_Income_median
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066.19,135.0,3.1,44033.0
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11,Yes,High,23066.19,106.0,8.2,215546.0
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01,No,Medium,28536.34,146.0,6.3,226403.0
3,101968,66.0,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869.71,115.0,9.7,87824.0
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03,No,High,34163.02,94.0,3.7,31570.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10,No,Medium,8455.42,119.0,8.6,88530.0
2036,101295,31.0,205738.0,270989.40,392,8,Mumbai,Corporate,Agent,2025-07-05,Yes,High,34087.69,134.0,2.6,205738.0
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17,Yes,Low,26518.74,87.0,1.3,211994.0
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26,No,Low,20943.11,107.0,9.3,30105.0
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,2023-08-26,Yes,Low,48511.32,119.0,3.1,248332.0

In [59]:
'''Q22. Clean Risk_Level
Check the distribution of:
High
Medium
Low
Verify whether missing values exist.
Then display the final class distribution.'''

df["Risk_Level"].value_counts()
df["Risk_Level"].isna().sum()

df["Risk_Level"].value_counts()
df

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,Annual_Income_median
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066.19,135.0,3.1,44033.0
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11,Yes,High,23066.19,106.0,8.2,215546.0
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01,No,Medium,28536.34,146.0,6.3,226403.0
3,101968,66.0,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869.71,115.0,9.7,87824.0
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03,No,High,34163.02,94.0,3.7,31570.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10,No,Medium,8455.42,119.0,8.6,88530.0
2036,101295,31.0,205738.0,270989.40,392,8,Mumbai,Corporate,Agent,2025-07-05,Yes,High,34087.69,134.0,2.6,205738.0
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17,Yes,Low,26518.74,87.0,1.3,211994.0
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26,No,Low,20943.11,107.0,9.3,30105.0
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,2023-08-26,Yes,Low,48511.32,119.0,3.1,248332.0

# Part 6 — Column Transformation

In [60]:
'''Q23. Rename columns
Rename these columns:
Customer_ID → Customer_ID
Annual_Income → AnnualIncome
Account_Balance → AccountBalance
Credit_Score → CreditScore
Tenure_Years → Tenure
Join_Date → CustomerJoinDate
Risk_Level → RiskLevel
Monthly_Spend → MonthlySpend
Satisfaction_Score → SatisfactionScore
Use rename().'''


df.rename(columns={
    "Customer_ID": "Customer_ID",
    "Annual_Income": "AnnualIncome",
    "Account_Balance": "AccountBalance",
    "Credit_Score": "CreditScore",
    "Tenure_Years": "Tenure",
    "Join_Date": "CustomerJoinDate",
    "Risk_Level": "RiskLevel",
    "Monthly_Spend": "MonthlySpend",
    "Satisfaction_Score": "SatisfactionScore"
}, inplace=True)


df

,Customer_ID,Age,AnnualIncome,AccountBalance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore,Annual_Income_median
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066.19,135.0,3.1,44033.0
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11,Yes,High,23066.19,106.0,8.2,215546.0
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01,No,Medium,28536.34,146.0,6.3,226403.0
3,101968,66.0,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869.71,115.0,9.7,87824.0
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03,No,High,34163.02,94.0,3.7,31570.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10,No,Medium,8455.42,119.0,8.6,88530.0
2036,101295,31.0,205738.0,270989.40,392,8,Mumbai,Corporate,Agent,2025-07-05,Yes,High,34087.69,134.0,2.6,205738.0
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17,Yes,Low,26518.74,87.0,1.3,211994.0
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26,No,Low,20943.11,107.0,9.3,30105.0
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,2023-08-26,Yes,Low,48511.32,119.0,3.1,248332.0

In [61]:
'''Q24. Add a prefix
Add:
Customer_
to every column.
Example:
Age
becomes:
Customer_Age
Use: add_prefix()'''

df = df.add_prefix("Customer_")

df

,Customer_Customer_ID,Customer_Age,Customer_AnnualIncome,Customer_AccountBalance,Customer_CreditScore,Customer_Tenure,Customer_City,Customer_Segment,Customer_Channel,Customer_CustomerJoinDate,Customer_Active,Customer_RiskLevel,Customer_MonthlySpend,Customer_Transactions,Customer_SatisfactionScore,Customer_Annual_Income_median
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066.19,135.0,3.1,44033.0
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11,Yes,High,23066.19,106.0,8.2,215546.0
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01,No,Medium,28536.34,146.0,6.3,226403.0
3,101968,66.0,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869.71,115.0,9.7,87824.0
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03,No,High,34163.02,94.0,3.7,31570.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10,No,Medium,8455.42,119.0,8.6,88530.0
2036,101295,31.0,205738.0,270989.40,392,8,Mumbai,Corporate,Agent,2025-07-05,Yes,High,34087.69,134.0,2.6,205738.0
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17,Yes,Low,26518.74,87.0,1.3,211994.0
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26,No,Low,20943.11,107.0,9.3,30105.0
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,2023-08-26,Yes,Low,48511.32,119.0,3.1,248332.0

In [63]:
'''Q25. Remove unnecessary column
Determine whether Customer_ID should be retained for analysis.
Create a cleaned DataFrame without the identifier column.
Use: drop()'''

cleaned_df = df.drop(columns=["Customer_Customer_ID"])

cleaned_df.head()
cleaned_df.columns

Index(['Customer_Age', 'Customer_AnnualIncome', 'Customer_AccountBalance',
       'Customer_CreditScore', 'Customer_Tenure', 'Customer_City',
       'Customer_Segment', 'Customer_Channel', 'Customer_CustomerJoinDate',
       'Customer_Active', 'Customer_RiskLevel', 'Customer_MonthlySpend',
       'Customer_Transactions', 'Customer_SatisfactionScore',
       'Customer_Annual_Income_median'],
      dtype='object')

# Part 7 — Create New Columns

In [66]:
'''Q26. Create Annual Income in Lakhs
Create:
Income_Lakhs
using:
AnnualIncome / 100000
Then check the first 10 records.'''


df["Income_Lakhs"] = df["Customer_AnnualIncome"] / 100000

df.head(10)

,Customer_Customer_ID,Customer_Age,Customer_AnnualIncome,Customer_AccountBalance,Customer_CreditScore,Customer_Tenure,Customer_City,Customer_Segment,Customer_Channel,Customer_CustomerJoinDate,Customer_Active,Customer_RiskLevel,Customer_MonthlySpend,Customer_Transactions,Customer_SatisfactionScore,Customer_Annual_Income_median,Income_Lakhs
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066.19,135.0,3.1,44033.0,0.44033
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11,Yes,High,23066.19,106.0,8.2,215546.0,2.15546
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01,No,Medium,28536.34,146.0,6.3,226403.0,2.26403
3,101968,66.0,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869.71,115.0,9.7,87824.0,0.87824
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03,No,High,34163.02,94.0,3.7,31570.0,0.31570
5,101334,68.0,37087.0,180084.44,738,1,Chennai,Premium,Agent,2023-06-04,Yes,Low,15121.16,6.0,8.5,37087.0,0.37087
6,100415,47.0,67229.0,99629.81,464,4,Chennai,Retail,Online,2024-01-16,Yes,High,17655.61,31.0,2.8,67229.0,0.67229
7,100983,65.0,67229.0,61030.94,554,15,Kolkata,SME,Agent,2024-06-26,Yes,Medium,1720.85,139.0,9.7,Annual_Income_median,0.67229
8,100417,63.0,153267.0,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12,Yes,High,38043.07,76.0,7.1,153267.0,1.53267
9,101472,42.0,153267.0,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07,Yes,Medium,11472.36,124.0,9.1,Annual_Income_median,1.53267

In [ ]:
Q28. Create Balance-to-Income Ratio
Create:
Balance_Income_Ratio
using:
AccountBalance / AnnualIncome
Then inspect the first 10 rows.
Think carefully about division by zero and missing values.

In [ ]:
Part 8 — Final Real-World Cleaning Challenge