In [254]:
#1. Load the Flight Price dataset into a Pandas DataFrame and display the first five rows.
import pandas as pd
df = pd.read_excel("C:/Users/anilr/Downloads/Data_Train.xlsx")
df.head(5)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [218]:
# 2. Find the number of rows and columns in the dataset.
df.shape

(10683, 11)

In [219]:
# 3. Display all column names in the dataset.
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

In [220]:
# 4. Display the data types of all columns.
df.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
dtype: object

In [221]:
# 5. Use df.info() to inspect the structure of the dataset.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [222]:
# 6. Check the number of missing values in each column.
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [223]:
# 7. Check the percentage of missing values in each column.
percentage = df.isnull().mean() * 100

print(percentage)

Airline            0.000000
Date_of_Journey    0.000000
Source             0.000000
Destination        0.000000
Route              0.009361
Dep_Time           0.000000
Arrival_Time       0.000000
Duration           0.000000
Total_Stops        0.009361
Additional_Info    0.000000
Price              0.000000
dtype: float64

In [224]:
# 8. Display the unique values and frequency of each value in the Airline column.
df["Airline"].value_counts()

Airline
Jet Airways                          3849
IndiGo                               2053
Air India                            1752
Multiple carriers                    1196
SpiceJet                              818
Vistara                               479
Air Asia                              319
GoAir                                 194
Multiple carriers Premium economy      13
Jet Airways Business                    6
Vistara Premium economy                 3
Trujet                                  1
Name: count, dtype: int64

In [225]:
# 9. Display the frequency distribution of Total_Stops, including missing values.
df["Total_Stops"].fillna("Missing").value_counts()

Total_Stops
1 stop      5625
non-stop    3491
2 stops     1520
3 stops       45
Missing        1
4 stops        1
Name: count, dtype: int64

In [226]:
# 10.Convert Date_of_Journey into a datetime format.
df["Date_of_Journey"] = pd.to_datetime(df["Date_of_Journey"],dayfirst=True)
df["Date_of_Journey"]

0       2019-03-24
1       2019-05-01
2       2019-06-09
3       2019-05-12
4       2019-03-01
           ...
10678   2019-04-09
10679   2019-04-27
10680   2019-04-27
10681   2019-03-01
10682   2019-05-09
Name: Date_of_Journey, Length: 10683, dtype: datetime64[ns]

In [227]:
# 11.Extract the day from Date_of_Journey and create a day column.
df["Day"] = df["Date_of_Journey"].dt.day
df["Day"]

0        24
1         1
2         9
3        12
4         1
         ..
10678     9
10679    27
10680    27
10681     1
10682     9
Name: Day, Length: 10683, dtype: int32

In [228]:
# 12.Extract the month from Date_of_Journey and create a month column.
df["month"] = df["Date_of_Journey"].dt.month
df["month"]

0        3
1        5
2        6
3        5
4        3
        ..
10678    4
10679    4
10680    4
10681    3
10682    5
Name: month, Length: 10683, dtype: int32

In [229]:
# 13.Extract the year from Date_of_Journey and create a year column.
df["year"] = df["Date_of_Journey"].dt.year
df["year"]

0        2019
1        2019
2        2019
3        2019
4        2019
         ...
10678    2019
10679    2019
10680    2019
10681    2019
10682    2019
Name: year, Length: 10683, dtype: int32

In [230]:
# 14.Drop the original Date_of_Journey column after extracting the require features.
df.drop("Date_of_Journey", axis=1, inplace=True)
df.head(2)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Day,month,year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019

In [231]:
# 15.Convert Dep_Time into datetime format and extract the departure hour into Dep_Hour.
df["Dep_Time"] = pd.to_datetime(df["Dep_Time"], format="%H:%M")

df["Dep_Hour"] = df["Dep_Time"].dt.hour

print(df[["Dep_Time", "Dep_Hour"]].head())

             Dep_Time  Dep_Hour
0 1900-01-01 22:20:00        22
1 1900-01-01 05:50:00         5
2 1900-01-01 09:25:00         9
3 1900-01-01 18:05:00        18
4 1900-01-01 16:50:00        16

In [232]:
# 16.Extract the departure minute from Dep_Time and create Dep_Minute.
df["Dep_Minute"] = df["Dep_Time"].dt.minute
df["Dep_Minute"]

0        20
1        50
2        25
3         5
4        50
         ..
10678    55
10679    45
10680    20
10681    30
10682    55
Name: Dep_Minute, Length: 10683, dtype: int32

In [233]:
# 17.Drop the original Dep_Time column after extracting the required features.
df.drop("Dep_Time", axis=1, inplace=True)
df

,Airline,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Day,month,year,Dep_Hour,Dep_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,7h 25m,2 stops,No info,7662,1,5,2019,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,23:30,5h 25m,1 stop,No info,6218,12,5,2019,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,21:35,4h 45m,1 stop,No info,13302,1,3,2019,16,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,22:25,2h 30m,non-stop,No info,4107,9,4,2019,19,55
10679,Air India,Kolkata,Banglore,CCU → BLR,23:20,2h 35m,non-stop,No info,4145,27,4,2019,20,45
10680,Jet Airways,Banglore,Delhi,BLR → DEL,11:20,3h,non-stop,No info,7229,27,4,2019,8,20
10681,Vistara,Banglore,New Delhi,BLR → DEL,14:10,2h 40m,non-stop,No info,12648,1,3,2019,11,30
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,19:15,8h 20m,2 stops,No info,11753,9,5,2019,10,55

In [234]:
# 18.Extract only the time portion from Arrival_Time.
df["Arrival_Time"] = pd.to_datetime(df["Arrival_Time"],format="%H:%M",errors="coerce").dt.time
df["Arrival_Time"]

0             NaT
1        13:15:00
2             NaT
3        23:30:00
4        21:35:00
           ...
10678    22:25:00
10679    23:20:00
10680    11:20:00
10681    14:10:00
10682    19:15:00
Name: Arrival_Time, Length: 10683, dtype: object

In [235]:
# 19.Extract the arrival hour and minute into Arrival_Hour and Arrival_Minute.
df["Arrival_Hour"] = pd.to_datetime(df["Arrival_Time"].astype(str),errors="coerce").dt.hour

df["Arrival_Minute"] = pd.to_datetime(df["Arrival_Time"].astype(str),errors="coerce").dt.minute
print(df[["Arrival_Time", "Arrival_Hour", "Arrival_Minute"]])

      Arrival_Time  Arrival_Hour  Arrival_Minute
0              NaT           NaN             NaN
1         13:15:00          13.0            15.0
2              NaT           NaN             NaN
3         23:30:00          23.0            30.0
4         21:35:00          21.0            35.0
...            ...           ...             ...
10678     22:25:00          22.0            25.0
10679     23:20:00          23.0            20.0
10680     11:20:00          11.0            20.0
10681     14:10:00          14.0            10.0
10682     19:15:00          19.0            15.0

[10683 rows x 3 columns]

C:\Users\anilr\AppData\Local\Temp\ipykernel_17356\2055387900.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Arrival_Hour"] = pd.to_datetime(df["Arrival_Time"].astype(str),errors="coerce").dt.hour
C:\Users\anilr\AppData\Local\Temp\ipykernel_17356\2055387900.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Arrival_Minute"] = pd.to_datetime(df["Arrival_Time"].astype(str),errors="coerce").dt.minute

In [236]:
# 20.Drop the original Arrival_Time column after extracting the required features.
df.drop(columns=["Arrival_Time"], inplace=True)
df

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Day,month,year,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,22,20,NaN,NaN
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,1,5,2019,5,50,13.0,15.0
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882,9,6,2019,9,25,NaN,NaN
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218,12,5,2019,18,5,23.0,30.0
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302,1,3,2019,16,50,21.0,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,2h 30m,non-stop,No info,4107,9,4,2019,19,55,22.0,25.0
10679,Air India,Kolkata,Banglore,CCU → BLR,2h 35m,non-stop,No info,4145,27,4,2019,20,45,23.0,20.0
10680,Jet Airways,Banglore,Delhi,BLR → DEL,3h,non-stop,No info,7229,27,4,2019,8,20,11.0,20.0
10681,Vistara,Banglore,New Delhi,BLR → DEL,2h 40m,non-stop,No info,12648,1,3,2019,11,30,14.0,10.0
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,8h 20m,2 stops,No info,11753,9,5,2019,10,55,19.0,15.0

In [237]:
# 21.Extract the hour component from Duration and create Duration_Hour. Handle invalid or missing extracted values appropriately.
df["Duration_Hour"] = pd.to_numeric(
    df["Duration"].astype(str).str.extract(r"(\d+)\s*h", expand=False),
    errors="coerce"
)

print(df[["Duration", "Duration_Hour"]].head())

  Duration  Duration_Hour
0   2h 50m            2.0
1   7h 25m            7.0
2      19h           19.0
3   5h 25m            5.0
4   4h 45m            4.0

In [238]:
# 22.Extract the minute component from Duration and create Duration_Minute. Handle invalid or missing extracted values appropriately.

In [239]:
# 23.Drop the original Duration column after creating the numerical duration features.
df["Duration_Minute"] = pd.to_numeric(
    df["Duration"].astype(str).str.extract(r"(\d+)\s*m", expand=False),
    errors="coerce"
)

print(df[["Duration", "Duration_Minute"]].head())

  Duration  Duration_Minute
0   2h 50m             50.0
1   7h 25m             25.0
2      19h              NaN
3   5h 25m             25.0
4   4h 45m             45.0

In [240]:
# 24.Replace non-stop in Total_Stops with 0 stops.
df["Total_Stops"] = df["Total_Stops"].replace("non-stop", 0)

df["Total_Stops"].value_counts(dropna=False)

Total_Stops
1 stop     5625
0          3491
2 stops    1520
3 stops      45
NaN           1
4 stops       1
Name: count, dtype: int64

In [241]:
# 25.Extract only the numerical value from Total_Stops and convert the column into an integer data type. Handle missing or invalid values appropriately
df["Total_Stops"] = pd.to_numeric(df["Total_Stops"].astype(str).str.extract(r"(\d+)", expand=False),errors="coerce")

df["Total_Stops"] = df["Total_Stops"].fillna(0).astype(int)

print(df["Total_Stops"].head())
print(df["Total_Stops"].dtype)

0    0
1    2
2    2
3    1
4    1
Name: Total_Stops, dtype: int64
int64

In [253]:
# 26.Split the Route column using → as the separator and create Route_1, Route_2, Route_3, Route_4, and Route_5.
df[["Route_1", "Route_2", "Route_3", "Route_4", "Route_5"]] = (df["Route"].str.split(" → ", expand=True))

print(df[["Route_1", "Route_2", "Route_3", "Route_4", "Route_5"]].head())

ValueError: Columns must be same length as key

In [249]:
# 27.Identify the missing values created in Route_3, Route_4, and Route_5 after splitting the route.
df[["Route_3", "Route_4", "Route_5"]].isnull().sum()

In [252]:
# 28.Replace the missing values in the route columns with an appropriate value such as None.
route_columns = ["Route_1", "Route_2", "Route_3", "Route_4", "Route_5"]

df[route_columns] = df[route_columns].fillna("None")

print(df[route_columns].head())

KeyError: "None of [Index(['Route_1', 'Route_2', 'Route_3', 'Route_4', 'Route_5'], dtype='object')] are in the [columns]"

In [ ]:
# 29.Drop the original Route column after creating and cleaning the route features.
df.drop("Route", axis=1, inplace=True)
df

In [ ]:
# 30.After completing all data cleaning and feature engineering, separate thedataset into X (independent variables) and y (target variable), 
# where Price is the target.