In [3]:
import pandas as pd
df = pd.read_csv("C:/Users/anilr/Downloads/Task_dataset (1).csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [4]:
#Challenge 1 – Complete Data Cleaning
#Your manager gives you a messy dataset.
#Perform all of the following:

#• Load the dataset.
import pandas as pd
df = pd.read_csv("C:/Users/anilr/Downloads/Task_dataset (1).csv")
print(df)

#• Display dataset information.
df.info()
print(df)

#• Find missing values.
df.isnull()
print(df)

#• Remove duplicate rows.
df.dropna(inplace = True)
print(df)

#• Fill missing values:
#o Age → median
Age_median = df["Age"].median()
Age_median
print(Age_median)
#o Balance → mean
Balance_median = df["Balance"].mean()
print(Balance_median)

#print(int(Balance_median))
#• Rename:
#o Target → CustomerStatus
df.rename(columns = {
    "Target":"CustomerStatus",
    
},inplace = True)
print(df)
#o AnnualIncome → Income
df.rename(columns = {
    "AnnualIncome":"Income",
    
},inplace = True)
print(df)
#• Display the first 15 rows.
#df.head(15)
##Methods expected:
#read_csv()
#info()
#isnull()
#drop_duplicates()
#median()
#mean()
#fillna()
#rename()
#head()

      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139          581        NaN
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB
      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139          581        NaN
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139          581        NaN
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
4          10005  66.0      108236.0      7198          394   75985.46
5          10006  69.0       31390.0     48323          770  107245.62
6          10007  58.0      182141.0     24200          891   38457.72
...          ...   ...           ...       ...          ...        ...
1011       10457  44.0       63604.0     27633          804  176354.13
1013       10531  64.0       85162.0     32083          654  132742.13
1014       10181  50.0      166466.0     44281          662   14415.10
1015       10450  43.0      173620.0      7121          644   60353.03
1017       10810  49.0       82062.0     47170          813   53850.09

      Tenure Geography  Gender    Segment Target
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
4          5        UK   Other  Corporate  Churn
5          6     India   Other  Corporate   Stay
6          1     India   Other     Retail  Churn
...      ...       ...     ...        ...    ...
1011       5   Germany  Female     Retail   Stay
1013      10    Canada    Male        SME   Stay
1014       0    Canada    Male  Corporate  Churn
1015       2       USA   Other  Corporate   Stay
1017       8   Germany  Female     Retail   Stay

[755 rows x 11 columns]
44.0
97451.61727152317
      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
4          10005  66.0      108236.0      7198          394   75985.46
5          10006  69.0       31390.0     48323          770  107245.62
6          10007  58.0      182141.0     24200          891   38457.72
...          ...   ...           ...       ...          ...        ...
1011       10457  44.0       63604.0     27633          804  176354.13
1013       10531  64.0       85162.0     32083          654  132742.13
1014       10181  50.0      166466.0     44281          662   14415.10
1015       10450  43.0      173620.0      7121          644   60353.03
1017       10810  49.0       82062.0     47170          813   53850.09

      Tenure Geography  Gender    Segment CustomerStatus
1          1       USA    Male        SME          Churn
2          8    Canada    Male  Corporate           Stay
4          5        UK   Other  Corporate          Churn
5          6     India   Other  Corporate           Stay
6          1     India   Other     Retail          Churn
...      ...       ...     ...        ...            ...
1011       5   Germany  Female     Retail           Stay
1013      10    Canada    Male        SME           Stay
1014       0    Canada    Male  Corporate          Churn
1015       2       USA   Other  Corporate           Stay
1017       8   Germany  Female     Retail           Stay

[755 rows x 11 columns]
      CustomerID   Age    Income  Spending  CreditScore    Balance  Tenure  \
1          10002  65.0  162964.0      6197          732    6356.54       1
2          10003  56.0   26956.0     37281          503  143203.92       8
4          10005  66.0  108236.0      7198          394   75985.46       5
5          10006  69.0   31390.0     48323          770  107245.62       6
6          10007  58.0  182141.0     24200          891   38457.72       1
...          ...   ...       ...       ...          ...        ...     ...
1011       10457  44.0   63604.0     27633          804  176354.13       5
1013       10531  64.0   85162.0     32083          654  132742.13      10
1014       10181  50.0  166466.0     44281          662   14415.10       0
1015       10450  43.0  173620.0      7121          644   60353.03       2
1017       10810  49.0   82062.0     47170          813   53850.09       8

     Geography  Gender    Segment CustomerStatus
1          USA    Male        SME          Churn
2       Canada    Male  Corporate           Stay
4           UK   Other  Corporate          Churn
5        India   Other  Corporate           Stay
6        India   Other     Retail          Churn
...        ...     ...        ...            ...
1011   Germany  Female     Retail           Stay
1013    Canada    Male        SME           Stay
1014    Canada    Male  Corporate          Churn
1015       USA   Other  Corporate           Stay
1017   Germany  Female     Retail           Stay

[755 rows x 11 columns]

In [5]:
#Challenge 2 – Banking Report
df = pd.read_csv("C:/Users/anilr/Downloads/Task_dataset (1).csv")
#The bank wants a numeric report.
#---->Tasks
#• Select only numeric columns.
df.select_dtypes(include = ["int"]).columns
print(df)
#• Display summary statistics.
df.describe()
print(df)
#• Convert Age and CreditScore to float.
df["CreditScore"] = df["CreditScore"].astype(float)
print(df["CreditScore"])
#• Display information again.
df.info
print(df)

      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139          581        NaN
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139          581        NaN
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
0       581.0
1       732.0
2       503.0
3       463.0
4       394.0
        ...
1015    644.0
1016    303.0
1017    813.0
1018    722.0
1019    430.0
Name: CreditScore, Length: 1020, dtype: float64
      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139        581.0        NaN
1          10002  65.0      162964.0      6197        732.0    6356.54
2          10003  56.0       26956.0     37281        503.0  143203.92
3          10004  55.0       92926.0       925        463.0  139627.88
4          10005  66.0      108236.0      7198        394.0   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0      173620.0      7121        644.0   60353.03
1016       10753  25.0       54490.0     13794        303.0  124512.07
1017       10810  49.0       82062.0     47170        813.0   53850.09
1018       10267  38.0           NaN     10424        722.0  138100.05
1019       10059  62.0       97504.0     36833        430.0        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]

In [6]:
#Challenge 3 – Duplicate Investigation
df = pd.read_csv("C:/Users/anilr/Downloads/Task_dataset (1).csv")
#Find duplicate customers.
duplicates = df[df.duplicated()]
print(duplicates)
#Then
#• Count duplicate rows.
df1 = df.duplicated().sum()
print(df1)
#• Remove duplicates.
df.dropna(inplace = True)
df
#• Print information before and after removing duplicates.
df.info()

#• Show the last 20 rows.
df.tail()

      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
1000       10643  41.0      125012.0     18825          761   35977.85
1001       10763  56.0      102965.0     17517          838  115028.54
1002       10910  66.0      118506.0      6296          306   81892.13
1003       10200  19.0      115052.0     20741          484  190233.86
1004       10587  29.0           NaN     40255          383  168358.60
1005       10798  22.0      176830.0      7626          688   65481.65
1006       10653  32.0           NaN     21266          598  142086.70
1007       10756  53.0       74430.0      3705          489   29651.23
1008       10417  70.0       40417.0     37956          681   23880.19
1009       10499  34.0      166546.0     12497          643  130886.93
1010       10515  62.0      199762.0     41808          309   60223.29
1011       10457  44.0       63604.0     27633          804  176354.13
1012       10882  61.0      115417.0      3879          413   76591.00
1013       10531  64.0       85162.0     32083          654  132742.13
1014       10181  50.0      166466.0     44281          662   14415.10
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
1000       2   Germany   Other     Retail   Stay
1001       9        UK     NaN        SME   Stay
1002       4    Canada    Male        SME  Churn
1003       5    Canada    Male     Retail  Churn
1004       2   Germany    Male  Corporate  Churn
1005      10    France    Male     Retail   Stay
1006       9    France  Female  Corporate   Stay
1007      10        UK    Male     Retail  Churn
1008      10     India    Male     Retail   Stay
1009       3        UK    Male        SME   Stay
1010      10     India   Other        SME  Churn
1011       5   Germany  Female     Retail   Stay
1012       7       NaN    Male  Corporate  Churn
1013      10    Canada    Male        SME   Stay
1014       0    Canada    Male  Corporate  Churn
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn
20
<class 'pandas.core.frame.DataFrame'>
Index: 755 entries, 1 to 1017
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    755 non-null    int64
 1   Age           755 non-null    float64
 2   AnnualIncome  755 non-null    float64
 3   Spending      755 non-null    int64
 4   CreditScore   755 non-null    int64
 5   Balance       755 non-null    float64
 6   Tenure        755 non-null    int64
 7   Geography     755 non-null    object
 8   Gender        755 non-null    object
 9   Segment       755 non-null    object
 10  Target        755 non-null    object
dtypes: float64(3), int64(4), object(4)
memory usage: 70.8+ KB

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
1011,10457,44.0,63604.0,27633,804,176354.13,5,Germany,Female,Retail,Stay
1013,10531,64.0,85162.0,32083,654,132742.13,10,Canada,Male,SME,Stay
1014,10181,50.0,166466.0,44281,662,14415.10,0,Canada,Male,Corporate,Churn
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay

In [7]:
#Challenge 4 – HR Department
df = pd.read_csv("C:/Users/anilr/Downloads/Task_dataset (1).csv")
#HR wants better column names.
df.columns
print(df)
#Rename
#CustomerID → Employee_ID
#Age → EmployeeAge
#Gender → EmployeeGender
#AnnualIncome → Salary
#Target → PromotionStatus
df.rename(columns = {
    "CustomerID":"Employee_ID",
    "Age":"EmployeeAge",
    "Gender":"EmployeeGender",
    "AnnualIncome":"Salary",
    "Target":"PromotionStatus"
},inplace = True)
print(df)
#Then
#• Add prefix
#HR_ to every column.
df.add_prefix("HR_")
print(df)
#Display 10 random records.
df.tail(10)
print(df)

      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139          581        NaN
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
      Employee_ID  EmployeeAge    Salary  Spending  CreditScore    Balance  \
0           10001         58.0   49184.0      2139          581        NaN
1           10002         65.0  162964.0      6197          732    6356.54
2           10003         56.0   26956.0     37281          503  143203.92
3           10004         55.0   92926.0       925          463  139627.88
4           10005         66.0  108236.0      7198          394   75985.46
...           ...          ...       ...       ...          ...        ...
1015        10450         43.0  173620.0      7121          644   60353.03
1016        10753         25.0   54490.0     13794          303  124512.07
1017        10810         49.0   82062.0     47170          813   53850.09
1018        10267         38.0       NaN     10424          722  138100.05
1019        10059         62.0   97504.0     36833          430        NaN

      Tenure Geography EmployeeGender    Segment PromotionStatus
0          2    France           Male        SME            Stay
1          1       USA           Male        SME           Churn
2          8    Canada           Male  Corporate            Stay
3          5       NaN           Male     Retail           Churn
4          5        UK          Other  Corporate           Churn
...      ...       ...            ...        ...             ...
1015       2       USA          Other  Corporate            Stay
1016       4     India            NaN  Corporate           Churn
1017       8   Germany         Female     Retail            Stay
1018       6   Germany          Other  Corporate            Stay
1019      10    Canada          Other        NaN           Churn

[1020 rows x 11 columns]
      Employee_ID  EmployeeAge    Salary  Spending  CreditScore    Balance  \
0           10001         58.0   49184.0      2139          581        NaN
1           10002         65.0  162964.0      6197          732    6356.54
2           10003         56.0   26956.0     37281          503  143203.92
3           10004         55.0   92926.0       925          463  139627.88
4           10005         66.0  108236.0      7198          394   75985.46
...           ...          ...       ...       ...          ...        ...
1015        10450         43.0  173620.0      7121          644   60353.03
1016        10753         25.0   54490.0     13794          303  124512.07
1017        10810         49.0   82062.0     47170          813   53850.09
1018        10267         38.0       NaN     10424          722  138100.05
1019        10059         62.0   97504.0     36833          430        NaN

      Tenure Geography EmployeeGender    Segment PromotionStatus
0          2    France           Male        SME            Stay
1          1       USA           Male        SME           Churn
2          8    Canada           Male  Corporate            Stay
3          5       NaN           Male     Retail           Churn
4          5        UK          Other  Corporate           Churn
...      ...       ...            ...        ...             ...
1015       2       USA          Other  Corporate            Stay
1016       4     India            NaN  Corporate           Churn
1017       8   Germany         Female     Retail            Stay
1018       6   Germany          Other  Corporate            Stay
1019      10    Canada          Other        NaN           Churn

[1020 rows x 11 columns]
      Employee_ID  EmployeeAge    Salary  Spending  CreditScore    Balance  \
0           10001         58.0   49184.0      2139          581        NaN
1           10002         65.0  162964.0      6197          732    6356.54
2           10003         56.0   26956.0     37281          503  143203.92
3           10004         55.0   92926.0       925          463  139627.88
4           10005         66.0  108236.0      7198          394   75985.46
...           ...          ...       ...       ...          ...        ...
1015        10450         43.0  173620.0      7121          644   60353.03
1016        10753         25.0   54490.0     13794          303  124512.07
1017        10810         49.0   82062.0     47170          813   53850.09
1018        10267         38.0       NaN     10424          722  138100.05
1019        10059         62.0   97504.0     36833          430        NaN

      Tenure Geography EmployeeGender    Segment PromotionStatus
0          2    France           Male        SME            Stay
1          1       USA           Male        SME           Churn
2          8    Canada           Male  Corporate            Stay
3          5       NaN           Male     Retail           Churn
4          5        UK          Other  Corporate           Churn
...      ...       ...            ...        ...             ...
1015       2       USA          Other  Corporate            Stay
1016       4     India            NaN  Corporate           Churn
1017       8   Germany         Female     Retail            Stay
1018       6   Germany          Other  Corporate            Stay
1019      10    Canada          Other        NaN           Churn

[1020 rows x 11 columns]

In [8]:
#Challenge 5 – Finance Cleaning
df = pd.read_csv("C:/Users/anilr/Downloads/Task_dataset (1).csv")

#Finance department reports missing values.
df.isnull().sum()
print(df)

##---->Tasks
#Fill
#AnnualIncome → Median
AnnualIncome_median = df["AnnualIncome"].median()
AnnualIncome_median
df["AnnualIncome"] = df["AnnualIncome"].fillna(AnnualIncome_median)
print(df["AnnualIncome"])

#Balance → Mean
Balance_Mean = df["Balance"].fillna(df["Balance"].mean())
print(Balance_Mean)

#Age → Median
Age_median = df["Age"].median()
Age_median
df["Age_median"] = df["Age"].fillna(AnnualIncome_median)
print(df["Age_median"])

#Then
#Generate descriptive statistics.
df.describe()

      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139          581        NaN
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
0        49184.0
1       162964.0
2        26956.0
3        92926.0
4       108236.0
          ...
1015    173620.0
1016     54490.0
1017     82062.0
1018    112358.0
1019     97504.0
Name: AnnualIncome, Length: 1020, dtype: float64
0        97523.535666
1         6356.540000
2       143203.920000
3       139627.880000
4        75985.460000
            ...
1015     60353.030000
1016    124512.070000
1017     53850.090000
1018    138100.050000
1019     97523.535666
Name: Balance, Length: 1020, dtype: float64
0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: Age_median, Length: 1020, dtype: float64

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Age_median
count,1020.000000,970.000000,1020.000000,1020.000000,1020.000000,969.000000,1020.000000,1020.000000
mean,10501.599020,44.249485,112498.242157,25232.615686,602.659804,97523.535666,5.261765,5549.825490
std,288.022115,15.521935,50925.015723,14219.393105,176.560690,55796.562543,3.185330,24261.447359
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000,18.000000
25%,10252.750000,30.250000,69223.000000,13134.750000,440.750000,50077.860000,2.000000,31.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000,45.500000
75%,10752.250000,58.000000,155570.750000,37956.000000,757.250000,143947.810000,8.000000,60.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000,112358.000000

In [9]:
#Challenge 6 – Data Type Audit
#The company says
df = pd.read_csv("C:/Users/anilr/Downloads/Task_dataset (1).csv")
#Age and AnnualIncome are stored incorrectly.
df.dropna(inplace = True)

#--->Tasks
#Convert
#Age → int

df["Age"] = df["Age"].astype(int)
df["Age"] 
#AnnualIncome → float
df["AnnualIncome"] = df["AnnualIncome"].astype(float)
df["AnnualIncome"] 
#Balance → float
df["Balance"] = df["Balance"].astype(float)
df["Balance"] 
#Target → string
df["Target"] = df["Target"].astype(str)
df["Target"] 
#Print information.
df.info

<bound method DataFrame.info of       CustomerID  Age  AnnualIncome  Spending  CreditScore    Balance  Tenure  \
1          10002   65      162964.0      6197          732    6356.54       1
2          10003   56       26956.0     37281          503  143203.92       8
4          10005   66      108236.0      7198          394   75985.46       5
5          10006   69       31390.0     48323          770  107245.62       6
6          10007   58      182141.0     24200          891   38457.72       1
...          ...  ...           ...       ...          ...        ...     ...
1011       10457   44       63604.0     27633          804  176354.13       5
1013       10531   64       85162.0     32083          654  132742.13      10
1014       10181   50      166466.0     44281          662   14415.10       0
1015       10450   43      173620.0      7121          644   60353.03       2
1017       10810   49       82062.0     47170          813   53850.09       8

     Geography  Gender    Segment Target
1          USA    Male        SME  Churn
2       Canada    Male  Corporate   Stay
4           UK   Other  Corporate  Churn
5        India   Other  Corporate   Stay
6        India   Other     Retail  Churn
...        ...     ...        ...    ...
1011   Germany  Female     Retail   Stay
1013    Canada    Male        SME   Stay
1014    Canada    Male  Corporate  Churn
1015       USA   Other  Corporate   Stay
1017   Germany  Female     Retail   Stay

[755 rows x 11 columns]>

In [10]:
#Challenge 7 – Customer Analytics
#Create a new DataFrame that
df = pd.read_csv("C:/Users/anilr/Downloads/Task_dataset (1).csv")

#• removes Segment
df.drop('Segment', axis = 1 , inplace = True)

#• removes Geography
df.drop('Geography', axis = 1 , inplace = True)

#• removes duplicate rows
df.dropna(inplace = True)
df
#Display

#• first 10 rows
df.head()
print(df)
#• dataset information
df.info()
print(df)
#• statistical summary
df.describe()
print(df)

      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
5          10006  69.0       31390.0     48323          770  107245.62
...          ...   ...           ...       ...          ...        ...
1012       10882  61.0      115417.0      3879          413   76591.00
1013       10531  64.0       85162.0     32083          654  132742.13
1014       10181  50.0      166466.0     44281          662   14415.10
1015       10450  43.0      173620.0      7121          644   60353.03
1017       10810  49.0       82062.0     47170          813   53850.09

      Tenure  Gender Target
1          1    Male  Churn
2          8    Male   Stay
3          5    Male  Churn
4          5   Other  Churn
5          6   Other   Stay
...      ...     ...    ...
1012       7    Male  Churn
1013      10    Male   Stay
1014       0    Male  Churn
1015       2   Other   Stay
1017       8  Female   Stay

[833 rows x 9 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 833 entries, 1 to 1017
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    833 non-null    int64
 1   Age           833 non-null    float64
 2   AnnualIncome  833 non-null    float64
 3   Spending      833 non-null    int64
 4   CreditScore   833 non-null    int64
 5   Balance       833 non-null    float64
 6   Tenure        833 non-null    int64
 7   Gender        833 non-null    object
 8   Target        833 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 65.1+ KB
      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
5          10006  69.0       31390.0     48323          770  107245.62
...          ...   ...           ...       ...          ...        ...
1012       10882  61.0      115417.0      3879          413   76591.00
1013       10531  64.0       85162.0     32083          654  132742.13
1014       10181  50.0      166466.0     44281          662   14415.10
1015       10450  43.0      173620.0      7121          644   60353.03
1017       10810  49.0       82062.0     47170          813   53850.09

      Tenure  Gender Target
1          1    Male  Churn
2          8    Male   Stay
3          5    Male  Churn
4          5   Other  Churn
5          6   Other   Stay
...      ...     ...    ...
1012       7    Male  Churn
1013      10    Male   Stay
1014       0    Male  Churn
1015       2   Other   Stay
1017       8  Female   Stay

[833 rows x 9 columns]
      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
5          10006  69.0       31390.0     48323          770  107245.62
...          ...   ...           ...       ...          ...        ...
1012       10882  61.0      115417.0      3879          413   76591.00
1013       10531  64.0       85162.0     32083          654  132742.13
1014       10181  50.0      166466.0     44281          662   14415.10
1015       10450  43.0      173620.0      7121          644   60353.03
1017       10810  49.0       82062.0     47170          813   53850.09

      Tenure  Gender Target
1          1    Male  Churn
2          8    Male   Stay
3          5    Male  Churn
4          5   Other  Churn
5          6   Other   Stay
...      ...     ...    ...
1012       7    Male  Churn
1013      10    Male   Stay
1014       0    Male  Churn
1015       2   Other   Stay
1017       8  Female   Stay

[833 rows x 9 columns]

In [11]:
#Challenge 8 – ML Dataset Preparation
#Prepare a machine learning dataset.
df = pd.read_csv("C:/Users/anilr/Downloads/Task_dataset (1).csv")
#---->Perform
#• Remove duplicates
df.dropna(inplace = True)
print(df)
#• Remove CustomerID
df.drop('CustomerID',axis = 1,inplace = True)
print(df)
#• Remove Segment
df.drop('Segment', axis = 1 ,inplace = True)
print(df)
#• Fill missing values
df.isna()
print(df)
#• Rename Target to Output
df.rename(columns = {"Target":"Output"},inplace = True)
print(df)
#Finally Display
#head()
df.head()
print(df)
#info()
df.info()
print(df)
#describe()
df.describe()
print(df)
#value_counts(Output)
df.value_counts
print(df)

      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
4          10005  66.0      108236.0      7198          394   75985.46
5          10006  69.0       31390.0     48323          770  107245.62
6          10007  58.0      182141.0     24200          891   38457.72
...          ...   ...           ...       ...          ...        ...
1011       10457  44.0       63604.0     27633          804  176354.13
1013       10531  64.0       85162.0     32083          654  132742.13
1014       10181  50.0      166466.0     44281          662   14415.10
1015       10450  43.0      173620.0      7121          644   60353.03
1017       10810  49.0       82062.0     47170          813   53850.09

      Tenure Geography  Gender    Segment Target
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
4          5        UK   Other  Corporate  Churn
5          6     India   Other  Corporate   Stay
6          1     India   Other     Retail  Churn
...      ...       ...     ...        ...    ...
1011       5   Germany  Female     Retail   Stay
1013      10    Canada    Male        SME   Stay
1014       0    Canada    Male  Corporate  Churn
1015       2       USA   Other  Corporate   Stay
1017       8   Germany  Female     Retail   Stay

[755 rows x 11 columns]
       Age  AnnualIncome  Spending  CreditScore    Balance  Tenure Geography  \
1     65.0      162964.0      6197          732    6356.54       1       USA
2     56.0       26956.0     37281          503  143203.92       8    Canada
4     66.0      108236.0      7198          394   75985.46       5        UK
5     69.0       31390.0     48323          770  107245.62       6     India
6     58.0      182141.0     24200          891   38457.72       1     India
...    ...           ...       ...          ...        ...     ...       ...
1011  44.0       63604.0     27633          804  176354.13       5   Germany
1013  64.0       85162.0     32083          654  132742.13      10    Canada
1014  50.0      166466.0     44281          662   14415.10       0    Canada
1015  43.0      173620.0      7121          644   60353.03       2       USA
1017  49.0       82062.0     47170          813   53850.09       8   Germany

      Gender    Segment Target
1       Male        SME  Churn
2       Male  Corporate   Stay
4      Other  Corporate  Churn
5      Other  Corporate   Stay
6      Other     Retail  Churn
...      ...        ...    ...
1011  Female     Retail   Stay
1013    Male        SME   Stay
1014    Male  Corporate  Churn
1015   Other  Corporate   Stay
1017  Female     Retail   Stay

[755 rows x 10 columns]
       Age  AnnualIncome  Spending  CreditScore    Balance  Tenure Geography  \
1     65.0      162964.0      6197          732    6356.54       1       USA
2     56.0       26956.0     37281          503  143203.92       8    Canada
4     66.0      108236.0      7198          394   75985.46       5        UK
5     69.0       31390.0     48323          770  107245.62       6     India
6     58.0      182141.0     24200          891   38457.72       1     India
...    ...           ...       ...          ...        ...     ...       ...
1011  44.0       63604.0     27633          804  176354.13       5   Germany
1013  64.0       85162.0     32083          654  132742.13      10    Canada
1014  50.0      166466.0     44281          662   14415.10       0    Canada
1015  43.0      173620.0      7121          644   60353.03       2       USA
1017  49.0       82062.0     47170          813   53850.09       8   Germany

      Gender Target
1       Male  Churn
2       Male   Stay
4      Other  Churn
5      Other   Stay
6      Other  Churn
...      ...    ...
1011  Female   Stay
1013    Male   Stay
1014    Male  Churn
1015   Other   Stay
1017  Female   Stay

[755 rows x 9 columns]
       Age  AnnualIncome  Spending  CreditScore    Balance  Tenure Geography  \
1     65.0      162964.0      6197          732    6356.54       1       USA
2     56.0       26956.0     37281          503  143203.92       8    Canada
4     66.0      108236.0      7198          394   75985.46       5        UK
5     69.0       31390.0     48323          770  107245.62       6     India
6     58.0      182141.0     24200          891   38457.72       1     India
...    ...           ...       ...          ...        ...     ...       ...
1011  44.0       63604.0     27633          804  176354.13       5   Germany
1013  64.0       85162.0     32083          654  132742.13      10    Canada
1014  50.0      166466.0     44281          662   14415.10       0    Canada
1015  43.0      173620.0      7121          644   60353.03       2       USA
1017  49.0       82062.0     47170          813   53850.09       8   Germany

      Gender Target
1       Male  Churn
2       Male   Stay
4      Other  Churn
5      Other   Stay
6      Other  Churn
...      ...    ...
1011  Female   Stay
1013    Male   Stay
1014    Male  Churn
1015   Other   Stay
1017  Female   Stay

[755 rows x 9 columns]
       Age  AnnualIncome  Spending  CreditScore    Balance  Tenure Geography  \
1     65.0      162964.0      6197          732    6356.54       1       USA
2     56.0       26956.0     37281          503  143203.92       8    Canada
4     66.0      108236.0      7198          394   75985.46       5        UK
5     69.0       31390.0     48323          770  107245.62       6     India
6     58.0      182141.0     24200          891   38457.72       1     India
...    ...           ...       ...          ...        ...     ...       ...
1011  44.0       63604.0     27633          804  176354.13       5   Germany
1013  64.0       85162.0     32083          654  132742.13      10    Canada
1014  50.0      166466.0     44281          662   14415.10       0    Canada
1015  43.0      173620.0      7121          644   60353.03       2       USA
1017  49.0       82062.0     47170          813   53850.09       8   Germany

      Gender Output
1       Male  Churn
2       Male   Stay
4      Other  Churn
5      Other   Stay
6      Other  Churn
...      ...    ...
1011  Female   Stay
1013    Male   Stay
1014    Male  Churn
1015   Other   Stay
1017  Female   Stay

[755 rows x 9 columns]
       Age  AnnualIncome  Spending  CreditScore    Balance  Tenure Geography  \
1     65.0      162964.0      6197          732    6356.54       1       USA
2     56.0       26956.0     37281          503  143203.92       8    Canada
4     66.0      108236.0      7198          394   75985.46       5        UK
5     69.0       31390.0     48323          770  107245.62       6     India
6     58.0      182141.0     24200          891   38457.72       1     India
...    ...           ...       ...          ...        ...     ...       ...
1011  44.0       63604.0     27633          804  176354.13       5   Germany
1013  64.0       85162.0     32083          654  132742.13      10    Canada
1014  50.0      166466.0     44281          662   14415.10       0    Canada
1015  43.0      173620.0      7121          644   60353.03       2       USA
1017  49.0       82062.0     47170          813   53850.09       8   Germany

      Gender Output
1       Male  Churn
2       Male   Stay
4      Other  Churn
5      Other   Stay
6      Other  Churn
...      ...    ...
1011  Female   Stay
1013    Male   Stay
1014    Male  Churn
1015   Other   Stay
1017  Female   Stay

[755 rows x 9 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 755 entries, 1 to 1017
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Age           755 non-null    float64
 1   AnnualIncome  755 non-null    float64
 2   Spending      755 non-null    int64
 3   CreditScore   755 non-null    int64
 4   Balance       755 non-null    float64
 5   Tenure        755 non-null    int64
 6   Geography     755 non-null    object
 7   Gender        755 non-null    object
 8   Output        755 non-null    object
dtypes: float64(3), int64(3), object(3)
memory usage: 59.0+ KB
       Age  AnnualIncome  Spending  CreditScore    Balance  Tenure Geography  \
1     65.0      162964.0      6197          732    6356.54       1       USA
2     56.0       26956.0     37281          503  143203.92       8    Canada
4     66.0      108236.0      7198          394   75985.46       5        UK
5     69.0       31390.0     48323          770  107245.62       6     India
6     58.0      182141.0     24200          891   38457.72       1     India
...    ...           ...       ...          ...        ...     ...       ...
1011  44.0       63604.0     27633          804  176354.13       5   Germany
1013  64.0       85162.0     32083          654  132742.13      10    Canada
1014  50.0      166466.0     44281          662   14415.10       0    Canada
1015  43.0      173620.0      7121          644   60353.03       2       USA
1017  49.0       82062.0     47170          813   53850.09       8   Germany

      Gender Output
1       Male  Churn
2       Male   Stay
4      Other  Churn
5      Other   Stay
6      Other  Churn
...      ...    ...
1011  Female   Stay
1013    Male   Stay
1014    Male  Churn
1015   Other   Stay
1017  Female   Stay

[755 rows x 9 columns]
       Age  AnnualIncome  Spending  CreditScore    Balance  Tenure Geography  \
1     65.0      162964.0      6197          732    6356.54       1       USA
2     56.0       26956.0     37281          503  143203.92       8    Canada
4     66.0      108236.0      7198          394   75985.46       5        UK
5     69.0       31390.0     48323          770  107245.62       6     India
6     58.0      182141.0     24200          891   38457.72       1     India
...    ...           ...       ...          ...        ...     ...       ...
1011  44.0       63604.0     27633          804  176354.13       5   Germany
1013  64.0       85162.0     32083          654  132742.13      10    Canada
1014  50.0      166466.0     44281          662   14415.10       0    Canada
1015  43.0      173620.0      7121          644   60353.03       2       USA
1017  49.0       82062.0     47170          813   53850.09       8   Germany

      Gender Output
1       Male  Churn
2       Male   Stay
4      Other  Churn
5      Other   Stay
6      Other  Churn
...      ...    ...
1011  Female   Stay
1013    Male   Stay
1014    Male  Churn
1015   Other   Stay
1017  Female   Stay

[755 rows x 9 columns]
       Age  AnnualIncome  Spending  CreditScore    Balance  Tenure Geography  \
1     65.0      162964.0      6197          732    6356.54       1       USA
2     56.0       26956.0     37281          503  143203.92       8    Canada
4     66.0      108236.0      7198          394   75985.46       5        UK
5     69.0       31390.0     48323          770  107245.62       6     India
6     58.0      182141.0     24200          891   38457.72       1     India
...    ...           ...       ...          ...        ...     ...       ...
1011  44.0       63604.0     27633          804  176354.13       5   Germany
1013  64.0       85162.0     32083          654  132742.13      10    Canada
1014  50.0      166466.0     44281          662   14415.10       0    Canada
1015  43.0      173620.0      7121          644   60353.03       2       USA
1017  49.0       82062.0     47170          813   53850.09       8   Germany

      Gender Output
1       Male  Churn
2       Male   Stay
4      Other  Churn
5      Other   Stay
6      Other  Churn
...      ...    ...
1011  Female   Stay
1013    Male   Stay
1014    Male  Churn
1015   Other   Stay
1017  Female   Stay

[755 rows x 9 columns]

In [12]:
#Challenge 9 – Column Transformation
df = pd.read_csv("C:/Users/anilr/Downloads/Task_dataset (1).csv")
#Create these new columns
#NetWorth = Balance + AnnualIncome
df['NetWorth'] = df['Balance'] + df['AnnualIncome']


#AgeAfterRetirement = Age + 20
df['AgeAfterRetirement'] = df['Age'] + 20


#DoubleCreditScore = CreditScore * 2
df['DoubleCreditScore'] = df['CreditScore'] * 2


#IncomePerMonth = AnnualIncome / 12
df['IncomePerMonth'] = df['AnnualIncome'] /12


#Then
#Display first 15 rows.
df.head(15)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay,NaN,78.0,1162,4098.666667
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn,169320.54,85.0,1464,13580.333333
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay,170159.92,76.0,1006,2246.333333
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn,232553.88,75.0,926,7743.833333
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn,184221.46,86.0,788,9019.666667
5,10006,69.0,31390.0,48323,770,107245.62,6,India,Other,Corporate,Stay,138635.62,89.0,1540,2615.833333
6,10007,58.0,182141.0,24200,891,38457.72,1,India,Other,Retail,Churn,220598.72,78.0,1782,15178.416667
7,10008,67.0,95861.0,5729,538,173296.73,6,UK,Female,SME,Stay,269157.73,87.0,1076,7988.416667
8,10009,41.0,62638.0,24760,663,41901.41,4,France,Other,SME,Stay,104539.41,61.0,1326,5219.833333
9,10010,22.0,179680.0,42113,475,106827.98,3,USA,Female,Corporate,Churn,286507.98,42.0,950,14973.333333
10,10011,NaN,187772.0,45599,870,43923.03,5,India,NaN,Retail,Stay,231695.03,NaN,1740,15647.666667
11,10012,69.0,102694.0,26790,574,13237.72,9,France,Female,Retail,Churn,115931.72,89.0,1148,8557.833333
12,10013,59.0,150870.0,26428,769,28574.32,2,USA,Other,SME,Stay,179444.32,79.0,1538,12572.500000
13,10014,52.0,88876.0,49456,898,85686.77,9,Canada,Female,Retail,Stay,174562.77,72.0,1796,7406.333333
14,10015,26.0,153569.0,32843,393,151156.43,1,USA,Other,Retail,Churn,304725.43,46.0,786,12797.416667

In [13]:
#Challenge 10 – Company Report
df = pd.read_csv("C:/Users/anilr/Downloads/Task_dataset (1).csv")
#Display
#• first five rows
df.head(5)


#• last five rows
df.tail(5)


#• ten random rows
df.sample(10)


#• dataset information
df.info()


#• descriptive statistics
df.describe()
#Finally rename
#Target → Customer_Status
df.rename(columns = {'Target':'Customer_Status'
},inplace = True)
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Customer_Status
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [14]:
#Challenge 11 – Missing Value Report
#Create a report showing
df = pd.read_csv("C:/Users/anilr/Downloads/Task_dataset (1).csv")
#• Total missing values
df.isnull().sum()
#• Numerical columns
df.select_dtypes(include = ["int"]).columns
#• Mean of Balance
df['Balance'] = df['Balance'].mean()
df['Balance']
#• Median of Age
AgeAge = df["Age"].median()
AgeAge
#• Fill missing values
df.dropna()
#• Display information again
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       1020 non-null   float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [20]:
#Challenge 12 – Customer Classification
df = pd.read_csv("C:/Users/anilr/Downloads/Task_dataset (1).csv")
df
#Count
#Stay
#Churn
df.value_counts('Target')
print(df)
#Then
#Rename
#Target → Customer_Class
df.rename(columns = {"Target":"Customer_Class"},inplace = True)
print(df)

      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139          581        NaN
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139          581        NaN
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Customer_Class
0          2    France    Male        SME           Stay
1          1       USA    Male        SME          Churn
2          8    Canada    Male  Corporate           Stay
3          5       NaN    Male     Retail          Churn
4          5        UK   Other  Corporate          Churn
...      ...       ...     ...        ...            ...
1015       2       USA   Other  Corporate           Stay
1016       4     India     NaN  Corporate          Churn
1017       8   Germany  Female     Retail           Stay
1018       6   Germany   Other  Corporate           Stay
1019      10    Canada   Other        NaN          Churn

[1020 rows x 11 columns]

In [26]:
#Challenge 13 – Sales Department
#Rename
#Balance → AccountBalance
#AnnualIncome → Salary
#CreditScore → CreditScore
df.rename(columns = {
    "Balance":"AccountBalance",
    "AnnualIncome":"Salary",
    "CreditScore":"CreditScore"
})
#Add prefix
#Sales_
df.add_prefix("Sales_")
#Then
#Display
#sample(20)
df.sample(20)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Customer_Class
907,10908,36.0,62936.0,48210,734,145721.10,6,USA,Other,SME,Stay
690,10691,42.0,192470.0,32606,838,124794.10,9,UK,Male,Corporate,Stay
541,10542,47.0,69959.0,47475,646,21553.15,6,India,Other,SME,Stay
432,10433,18.0,36166.0,15067,433,39626.61,6,UK,Other,SME,Churn
43,10044,31.0,109884.0,13842,570,101081.81,4,India,Male,SME,Stay
878,10879,43.0,68482.0,24775,775,140780.41,0,France,Male,Corporate,Churn
15,10016,68.0,198384.0,28166,365,76953.46,9,Canada,Other,Corporate,Churn
419,10420,57.0,83591.0,30903,677,118338.19,7,USA,Other,SME,Stay
414,10415,33.0,32053.0,31417,672,76595.89,2,USA,Male,SME,Stay
689,10690,29.0,28198.0,13743,409,97074.06,1,India,Other,SME,Churn
623,10624,41.0,82719.0,43427,300,195129.18,1,UK,Female,Corporate,Churn
195,10196,56.0,33727.0,41845,642,13182.37,1,Germany,Other,Corporate,Churn
778,10779,64.0,29582.0,30605,696,142735.48,8,India,Male,Corporate,Stay
561,10562,38.0,157729.0,14915,488,104121.26,8,USA,Female,SME,Churn
609,10610,70.0,20314.0,44970,741,104408.85,5,India,Other,SME,Stay
905,10906,41.0,124217.0,10195,737,73925.99,5,India,Female,Corporate,Stay
523,10524,40.0,134744.0,41250,574,175695.11,1,NaN,Female,Retail,Churn
486,10487,40.0,62864.0,17451,392,57013.88,6,India,Male,SME,Churn
322,10323,27.0,22396.0,14834,817,91201.93,0,Germany,Other,SME,Churn
676,10677,30.0,NaN,3913,523,194654.81,3,France,NaN,Corporate,Stay

In [30]:
#Challenge 14 – Interview Challenge
#Without creating another DataFrame,
#perform
#• remove duplicates
df.duplicated().sum()
print(df)
#• rename Target
df.rename(columns = {'Customer_Class':'Target'},inplace = True)
print(df)
#• fill missing values
#• convert Balance to float
#• display summary
df.describe()
print(df)

      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139          581        NaN
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139          581        NaN
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139          581        NaN
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]

In [38]:
#Challenge 15 – Data Engineer Task
#Load the dataset.
df = pd.read_csv("C:/Users/anilr/Downloads/Task_dataset (1).csv")
#Create another DataFrame containing only numeric columns.
s = df.select_dtypes(include = ["float"]).columns
len(s)
#Drop
#CustomerID
#Target
df.drop('CustomerID', axis = 1 ,inplace = True)
df.drop('Target', axis = 1 ,inplace = True)
print(df)
#Display summary.
df.describe()

       Age  AnnualIncome  Spending  CreditScore    Balance  Tenure Geography  \
0     58.0       49184.0      2139          581        NaN       2    France
1     65.0      162964.0      6197          732    6356.54       1       USA
2     56.0       26956.0     37281          503  143203.92       8    Canada
3     55.0       92926.0       925          463  139627.88       5       NaN
4     66.0      108236.0      7198          394   75985.46       5        UK
...    ...           ...       ...          ...        ...     ...       ...
1015  43.0      173620.0      7121          644   60353.03       2       USA
1016  25.0       54490.0     13794          303  124512.07       4     India
1017  49.0       82062.0     47170          813   53850.09       8   Germany
1018  38.0           NaN     10424          722  138100.05       6   Germany
1019  62.0       97504.0     36833          430        NaN      10    Canada

      Gender    Segment
0       Male        SME
1       Male        SME
2       Male  Corporate
3       Male     Retail
4      Other  Corporate
...      ...        ...
1015   Other  Corporate
1016     NaN  Corporate
1017  Female     Retail
1018   Other  Corporate
1019   Other        NaN

[1020 rows x 9 columns]

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000
mean,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330
min,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000
50%,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000
75%,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000
max,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [122]:
#Challenge 16 – Mixed Cleaning
#Perform
df = pd.read_csv("C:/Users/anilr/Downloads/Task_dataset (1).csv")

#drop_duplicates()
df.drop_duplicates()
print(df)

#fillna()
df["Age"].fillna(method = "ffill",inplace = True)
print(df)

#astype()
df["Age"] = df["Age"].astype(float)
print(df)
#rename()
df.rename(columns={"Age": "new_age"}, inplace=True)
print(df)
#head()
df.head()
print(df)

#info()
df.info()

#using only one DataFrame variable.

      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139          581        NaN
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139          581        NaN
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139          581        NaN
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
      CustomerID  new_age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001     58.0       49184.0      2139          581        NaN
1          10002     65.0      162964.0      6197          732    6356.54
2          10003     56.0       26956.0     37281          503  143203.92
3          10004     55.0       92926.0       925          463  139627.88
4          10005     66.0      108236.0      7198          394   75985.46
...          ...      ...           ...       ...          ...        ...
1015       10450     43.0      173620.0      7121          644   60353.03
1016       10753     25.0       54490.0     13794          303  124512.07
1017       10810     49.0       82062.0     47170          813   53850.09
1018       10267     38.0           NaN     10424          722  138100.05
1019       10059     62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
      CustomerID  new_age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001     58.0       49184.0      2139          581        NaN
1          10002     65.0      162964.0      6197          732    6356.54
2          10003     56.0       26956.0     37281          503  143203.92
3          10004     55.0       92926.0       925          463  139627.88
4          10005     66.0      108236.0      7198          394   75985.46
...          ...      ...           ...       ...          ...        ...
1015       10450     43.0      173620.0      7121          644   60353.03
1016       10753     25.0       54490.0     13794          303  124512.07
1017       10810     49.0       82062.0     47170          813   53850.09
1018       10267     38.0           NaN     10424          722  138100.05
1019       10059     62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   new_age       1020 non-null   float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

C:\Users\anilr\AppData\Local\Temp\ipykernel_12088\1216112986.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(method = "ffill",inplace = True)
C:\Users\anilr\AppData\Local\Temp\ipykernel_12088\1216112986.py:10: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "ffill",inplace = True)

In [59]:
#Challenge 17 – Real Company Dataset
#Manager asks
#Remove duplicate records
df.dropna()
df
#Fill missing values
df.isnull()
#Rename all business columns

#Add company prefix
df.add_prefix('company__')
#Display summary
df.describe()
#Display target counts
df.info('Tenure')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   new_age       1020 non-null   float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [67]:
#Challenge 18 – Customer Summary
#Generate
df = pd.read_csv("C:/Users/anilr/Downloads/Task_dataset (1).csv")
#Mean Balance
df['Balance'] = df['Balance'].mean()
df['Balance']
#Median Balance
df['Balance_median'] = df["Balance"].median()
AnnualIncome_median
df["Balance_median"] = df["Balance"].fillna(AnnualIncome_median)
print(df["Balance_median"])

#Mean Age
df['Age_Mean'] = df['Age'].mean()
df['Age_Mean']
df["Age_Mean"] = df["Age"].fillna(AnnualIncome_median)
print(df["Age_Mean"])

#Median AnnualIncome
df['AnnualIncome_median'] = df["AnnualIncome"].median()
AnnualIncome_median
df["AnnualIncome_median"] = df["AnnualIncome"].fillna(AnnualIncome_median)
print(df["AnnualIncome_median"])
#Then
#fill missing values using these statistics.

0       97523.535666
1       97523.535666
2       97523.535666
3       97523.535666
4       97523.535666
            ...
1015    97523.535666
1016    97523.535666
1017    97523.535666
1018    97523.535666
1019    97523.535666
Name: Balance_median, Length: 1020, dtype: float64
0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: Age_Mean, Length: 1020, dtype: float64
0        49184.0
1       162964.0
2        26956.0
3        92926.0
4       108236.0
          ...
1015    173620.0
1016     54490.0
1017     82062.0
1018    112358.0
1019     97504.0
Name: AnnualIncome_median, Length: 1020, dtype: float64

In [92]:
#Challenge 19 – Transformation Challenge
df = pd.read_csv("C:/Users/anilr/Downloads/Task_dataset (1).csv")
print(df)
#Create
#Income_in_Lakhs
df['AnnualIncome'] = df['AnnualIncome'] /100000
print(df)
#Balance_in_Lakhs
df['Balance'] = df['Balance'] /100000
print(df)
#SeniorCitizen
df["SeniorCitizen"] = ["older"if age > 45 else "Young "for age in df["Age"]]
print(df["SeniorCitizen"])
#HighCreditScore
df["CreditScore_avg"] = ["HighCreditScore"if age > 500 else "LowCreditScore "for age in df["CreditScore"]]
print(df["CreditScore_avg"])
print(df)
#where
#SeniorCitizen = Age + 0
df["SeniorCitizen"]  = df["Age"]  + 0
print(df["SeniorCitizen"])
#HighCreditScore = CreditScore * 1
df["CreditScore_avg"] = df["CreditScore"] * 1
print(df["CreditScore_avg"])
#(No conditional statements.)

      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139          581        NaN
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       0.49184      2139          581        NaN
1          10002  65.0       1.62964      6197          732    6356.54
2          10003  56.0       0.26956     37281          503  143203.92
3          10004  55.0       0.92926       925          463  139627.88
4          10005  66.0       1.08236      7198          394   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0       1.73620      7121          644   60353.03
1016       10753  25.0       0.54490     13794          303  124512.07
1017       10810  49.0       0.82062     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       0.97504     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
      CustomerID   Age  AnnualIncome  Spending  CreditScore   Balance  Tenure  \
0          10001  58.0       0.49184      2139          581       NaN       2
1          10002  65.0       1.62964      6197          732  0.063565       1
2          10003  56.0       0.26956     37281          503  1.432039       8
3          10004  55.0       0.92926       925          463  1.396279       5
4          10005  66.0       1.08236      7198          394  0.759855       5
...          ...   ...           ...       ...          ...       ...     ...
1015       10450  43.0       1.73620      7121          644  0.603530       2
1016       10753  25.0       0.54490     13794          303  1.245121       4
1017       10810  49.0       0.82062     47170          813  0.538501       8
1018       10267  38.0           NaN     10424          722  1.381000       6
1019       10059  62.0       0.97504     36833          430       NaN      10

     Geography  Gender    Segment Target
0       France    Male        SME   Stay
1          USA    Male        SME  Churn
2       Canada    Male  Corporate   Stay
3          NaN    Male     Retail  Churn
4           UK   Other  Corporate  Churn
...        ...     ...        ...    ...
1015       USA   Other  Corporate   Stay
1016     India     NaN  Corporate  Churn
1017   Germany  Female     Retail   Stay
1018   Germany   Other  Corporate   Stay
1019    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
0        older
1        older
2        older
3        older
4        older
         ...
1015    Young
1016    Young
1017     older
1018    Young
1019     older
Name: SeniorCitizen, Length: 1020, dtype: object
0       HighCreditScore
1       HighCreditScore
2       HighCreditScore
3       LowCreditScore
4       LowCreditScore
             ...
1015    HighCreditScore
1016    LowCreditScore
1017    HighCreditScore
1018    HighCreditScore
1019    LowCreditScore
Name: CreditScore_avg, Length: 1020, dtype: object
      CustomerID   Age  AnnualIncome  Spending  CreditScore   Balance  Tenure  \
0          10001  58.0       0.49184      2139          581       NaN       2
1          10002  65.0       1.62964      6197          732  0.063565       1
2          10003  56.0       0.26956     37281          503  1.432039       8
3          10004  55.0       0.92926       925          463  1.396279       5
4          10005  66.0       1.08236      7198          394  0.759855       5
...          ...   ...           ...       ...          ...       ...     ...
1015       10450  43.0       1.73620      7121          644  0.603530       2
1016       10753  25.0       0.54490     13794          303  1.245121       4
1017       10810  49.0       0.82062     47170          813  0.538501       8
1018       10267  38.0           NaN     10424          722  1.381000       6
1019       10059  62.0       0.97504     36833          430       NaN      10

     Geography  Gender    Segment Target SeniorCitizen  CreditScore_avg
0       France    Male        SME   Stay         older  HighCreditScore
1          USA    Male        SME  Churn         older  HighCreditScore
2       Canada    Male  Corporate   Stay         older  HighCreditScore
3          NaN    Male     Retail  Churn         older  LowCreditScore
4           UK   Other  Corporate  Churn         older  LowCreditScore
...        ...     ...        ...    ...           ...              ...
1015       USA   Other  Corporate   Stay        Young   HighCreditScore
1016     India     NaN  Corporate  Churn        Young   LowCreditScore
1017   Germany  Female     Retail   Stay         older  HighCreditScore
1018   Germany   Other  Corporate   Stay        Young   HighCreditScore
1019    Canada   Other        NaN  Churn         older  LowCreditScore

[1020 rows x 13 columns]
0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: SeniorCitizen, Length: 1020, dtype: float64
0       581
1       732
2       503
3       463
4       394
       ...
1015    644
1016    303
1017    813
1018    722
1019    430
Name: CreditScore_avg, Length: 1020, dtype: int64

In [121]:
#Challenge 20 – Final Interview Project
#Your manager gives you a dirty customer dataset.
#Prepare the final dataset.
#Requirements
#Load datase
df = pd.read_csv("C:/Users/anilr/Downloads/Task_dataset (1).csv")
df
#Check information
df.info()
print(df)
#Find missing values
df.isnull()
print(df)
#Remove duplicates
df.dropna()
print(df)
#Rename
#CustomerID
#AnnualIncome
#CreditScore
#Target
df.rename(columns = {
    "CustomerID":"Customer_ID",
    "AnnualIncome":"Annual_Income",
    "CreditScore":"Credit_Score",
    "Target":"Output"
},inplace = True)
print(df)

#Convert
#Age
#AnnualIncome
#Balance
#Fill missing values
#Remove
#Segment
#CustomerID
#Create new columns
#TotalMoney = Balance + AnnualIncome
#df['TotalMoney'] = df['Balance'] + df['Annual_Income']

#AgeAfter5Years = Age + 5
#df['AgeAfter5Years'] = df['Age'] + 5
#df['AgeAfter5Years']


#MonthlyIncome = AnnualIncome / 12
#df['MonthlyIncome'] = df['Annual_Income'] / 12
#CreditScoreDouble = CreditScore * 2Display
#df['CreditScoreDouble'] = df['Credit_Score'] * 2
#df['CreditScoreDouble']
#• Head
df.head()
print(df)
#• Tail
df.tail()
print(df)
#• Sample
df.sample()
print(df)
#• Describe
df.describe()
print(df)
#• Target counts

#• Final information
df.info
print(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB
      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139          581        NaN
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139          581        NaN
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139          581        NaN
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
      Customer_ID   Age  Annual_Income  Spending  Credit_Score    Balance  \
0           10001  58.0        49184.0      2139           581        NaN
1           10002  65.0       162964.0      6197           732    6356.54
2           10003  56.0        26956.0     37281           503  143203.92
3           10004  55.0        92926.0       925           463  139627.88
4           10005  66.0       108236.0      7198           394   75985.46
...           ...   ...            ...       ...           ...        ...
1015        10450  43.0       173620.0      7121           644   60353.03
1016        10753  25.0        54490.0     13794           303  124512.07
1017        10810  49.0        82062.0     47170           813   53850.09
1018        10267  38.0            NaN     10424           722  138100.05
1019        10059  62.0        97504.0     36833           430        NaN

      Tenure Geography  Gender    Segment Output
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
      Customer_ID   Age  Annual_Income  Spending  Credit_Score    Balance  \
0           10001  58.0        49184.0      2139           581        NaN
1           10002  65.0       162964.0      6197           732    6356.54
2           10003  56.0        26956.0     37281           503  143203.92
3           10004  55.0        92926.0       925           463  139627.88
4           10005  66.0       108236.0      7198           394   75985.46
...           ...   ...            ...       ...           ...        ...
1015        10450  43.0       173620.0      7121           644   60353.03
1016        10753  25.0        54490.0     13794           303  124512.07
1017        10810  49.0        82062.0     47170           813   53850.09
1018        10267  38.0            NaN     10424           722  138100.05
1019        10059  62.0        97504.0     36833           430        NaN

      Tenure Geography  Gender    Segment Output
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
      Customer_ID   Age  Annual_Income  Spending  Credit_Score    Balance  \
0           10001  58.0        49184.0      2139           581        NaN
1           10002  65.0       162964.0      6197           732    6356.54
2           10003  56.0        26956.0     37281           503  143203.92
3           10004  55.0        92926.0       925           463  139627.88
4           10005  66.0       108236.0      7198           394   75985.46
...           ...   ...            ...       ...           ...        ...
1015        10450  43.0       173620.0      7121           644   60353.03
1016        10753  25.0        54490.0     13794           303  124512.07
1017        10810  49.0        82062.0     47170           813   53850.09
1018        10267  38.0            NaN     10424           722  138100.05
1019        10059  62.0        97504.0     36833           430        NaN

      Tenure Geography  Gender    Segment Output
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
      Customer_ID   Age  Annual_Income  Spending  Credit_Score    Balance  \
0           10001  58.0        49184.0      2139           581        NaN
1           10002  65.0       162964.0      6197           732    6356.54
2           10003  56.0        26956.0     37281           503  143203.92
3           10004  55.0        92926.0       925           463  139627.88
4           10005  66.0       108236.0      7198           394   75985.46
...           ...   ...            ...       ...           ...        ...
1015        10450  43.0       173620.0      7121           644   60353.03
1016        10753  25.0        54490.0     13794           303  124512.07
1017        10810  49.0        82062.0     47170           813   53850.09
1018        10267  38.0            NaN     10424           722  138100.05
1019        10059  62.0        97504.0     36833           430        NaN

      Tenure Geography  Gender    Segment Output
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
      Customer_ID   Age  Annual_Income  Spending  Credit_Score    Balance  \
0           10001  58.0        49184.0      2139           581        NaN
1           10002  65.0       162964.0      6197           732    6356.54
2           10003  56.0        26956.0     37281           503  143203.92
3           10004  55.0        92926.0       925           463  139627.88
4           10005  66.0       108236.0      7198           394   75985.46
...           ...   ...            ...       ...           ...        ...
1015        10450  43.0       173620.0      7121           644   60353.03
1016        10753  25.0        54490.0     13794           303  124512.07
1017        10810  49.0        82062.0     47170           813   53850.09
1018        10267  38.0            NaN     10424           722  138100.05
1019        10059  62.0        97504.0     36833           430        NaN

      Tenure Geography  Gender    Segment Output
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
      Customer_ID   Age  Annual_Income  Spending  Credit_Score    Balance  \
0           10001  58.0        49184.0      2139           581        NaN
1           10002  65.0       162964.0      6197           732    6356.54
2           10003  56.0        26956.0     37281           503  143203.92
3           10004  55.0        92926.0       925           463  139627.88
4           10005  66.0       108236.0      7198           394   75985.46
...           ...   ...            ...       ...           ...        ...
1015        10450  43.0       173620.0      7121           644   60353.03
1016        10753  25.0        54490.0     13794           303  124512.07
1017        10810  49.0        82062.0     47170           813   53850.09
1018        10267  38.0            NaN     10424           722  138100.05
1019        10059  62.0        97504.0     36833           430        NaN

      Tenure Geography  Gender    Segment Output
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]