# Pandas + NumPy Data Cleaning

In [10]:
# 1. Load the CSV using Pandas and display the first 10 rows.
import pandas as pd
df = pd.read_csv("C:\\Users\\anilr\\Downloads\\customer_data - customer_data.csv")
df.head(10)

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
5,CUST-01274,NaN,"$44,696",NaN,1.700044,12.0,NaN,Bengaluru,SMB,Male,Yes,Yes,21/07/2024,NaN,follow-up needed
6,CUST-00939,49.28347358,44108.07925,793.2135773,10.077820,7.0,3.872187,Kolkata,Consumer,NaN,yes,Yes,2023-08-14,google_ads,NaN
7,CUST-01732,37.63000983,80888.86264,850,4.489813,11.0,NaN,Pune,NaN,Female,N,No,NaN,NaN,good customer
8,CUST-00066,47.52016682,50011.55556,796.794099,9.074520,4.0,3.694925,Pune,SMB.,m,No,NaN,2021-03-08,Social,NaN
9,CUST-01324,NaN,84410.30824,482.3950729,6.820629,3.0,2.636945,Mumbai,Consumer,M,no,No,2024-09-10,Website,normal

In [2]:
# 2. Check the number of rows and columns in the dataset.
df.shape

(2000, 15)

In [9]:
# 3. Display all column names and identify which column names contain  leading/trailing spaces or inconsistent capitalization.  
for i in df.columns:
    print(i)

    if i != i.title():
        df = df.rename(columns = {i:i.title()})
        print(df)

Customer Id
Age
Income_Usd
Credit Score
Tenure_Years
Monthly_Visits
Satisfaction
City
Customer_Segment
Gender
Is_Active
Churn_Flag
Signup_Date
Lead_Source
Notes_Text

In [4]:
# 4. Check the data type of every column using Pandas. 
df.dtypes

Customer Id          object
Age                  object
Income_Usd           object
Credit Score         object
Tenure_Years        float64
Monthly_Visits      float64
Satisfaction        float64
City                 object
Customer_Segment     object
Gender               object
Is_Active            object
Churn_Flag           object
Signup_Date          object
Lead_Source          object
Notes_Text           object
dtype: object

In [5]:
# 5 calculate the number and persentage of missing valuse in every column.uyy

(df.isna().sum() / len(df)) * 100

Customer Id          1.00
Age                 16.55
Income_Usd          22.00
Credit Score        18.00
Tenure_Years        12.90
Monthly_Visits      14.00
Satisfaction        19.95
City                15.00
Customer_Segment    19.00
Gender              12.00
Is_Active           17.00
Churn_Flag           8.00
Signup_Date         12.00
Lead_Source         21.00
Notes_Text          32.80
dtype: float64

In [11]:
# 6. Find the rows where Customer ID is missing. 
df[df["Customer ID"].isna()]

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
162,NaN,18,61780.99213,715.4452325,10.137001,5.0,3.179153,Delhi,UNKNOWN,Female,NaN,No,2021-04-22,website,follow-up needed
226,NaN,18,58188.80528,737.9284458,15.655950,12.0,3.330254,Chennai,Consumer,Female,Y,NaN,2022-03-18,Referral,normal
300,NaN,NaN,93665.74378,703.9692987,12.723292,7.0,NaN,Pune,SMB,Female,1,No,NaN,Email,follow-up needed
421,NaN,29.6 years,NaN,641.3441152,8.940646,5.0,3.687539,NaN,Consumer,Female,1,No,2021-12-05,Unknown,NaN
770,NaN,20.39545706,92366.06753,767.8048841,4.524943,3.0,4.358065,Mumbai,Enterprise,f,N,No,2021-09-05,???,NaN
821,NaN,46.41996378,81119.71831,597.3307848,1.076200,5.0,4.346306,Delhi,consumer,f,1,Yes,2022-12-26,Email,NaN
876,NaN,36.57634009,76629.87047,699.109735,4.977078,6.0,2.700057,Mumbai,consumer,M,N,Yes,2021-07-01,referral,good
993,NaN,47.54933612,NaN,NaN,0.693710,4.0,3.659781,NaN,Enterprise,NaN,NaN,No,2024-07-09,Referral,late payment
1023,NaN,NaN,34219.41505,NaN,3.779121,4.0,3.529211,Hyderabad,NaN,M,N,No,2023-07-05,Google Ads,ok
1188,NaN,28.97406958,NaN,744 pts,7.947965,8.0,2.379383,Hyderabad,Consumer,f,Yes,No,2026-06-06,NaN,urgent
1202,NaN,42.23152645,35310.77625,684.8618643,2.465432,6.0,4.979391,Delhi,SMB,m,1,No,2024-10-10,google_ads,late payment
1212,NaN,56.44358785,"$99,697",749.3298384,3.743193,6.0,NaN,NaN,NaN,M,Y,Yes,2024-07-18,WEB,NaN
1248,NaN,34.60645101,96811.19575,798.1150352,1.551247,5.0,3.288656,Mumbai,SMB.,M,N,No,2023-09-16,Social,follow-up needed
1338,NaN,26.5 years,"$89,682",692.0794813,1.877392,4.0,3.783551,Pune,Consumer,m,N,No,2023-12-04,WEB,NaN
1346,NaN,46.22898842,60122.78196,684.8548451,3.837557,2.0,4.267750,Mumbai,consumer,F,N,Yes,2023-01-01,referral,follow-up needed
1448,NaN,18,NaN,628.337014,7.137356,5.0,NaN,Pune,Enterprise,Female,no,NaN,2024-08-25,Google Ads,NaN
1451,NaN,47.20187446,28270.08329,549.3662455,3.019237,6.0,3.441021,Hyderabad,SMB,m,yes,Yes,2023-10-12,Unknown,good
1462,NaN,49.99203599,58348.28529,511.5806801,2.775352,NaN,NaN,Mumbai,SMB,Female,no,No,2024-07-07,NaN,NaN
1564,NaN,42.96550781,"$64,045",561 pts,4.549291,4.0,3.513904,Chennai,Consumer,m,No,No,03/08/2023,Email,NaN
1652,NaN,33.27510593,37475.10034,NaN,4.345689,11.0,-999.000000,Mumbai,SMB,f,NaN,NaN,2022-02-15,Social,ok

In [12]:
# 7. Remove leading/trailing whitespace from all column names and convert them  to lowercase with underscores.  
df.columns.str.replace(" ","_",regex = True)

Index(['Customer_ID', 'Age', 'income_usd', 'credit_Score', 'tenure_years',
       'monthly_visits', 'satisfaction', 'City', 'customer_segment', 'gender',
       'is_active', 'churn_flag', 'signup_date', 'lead_source', 'notes_text'],
      dtype='object')

In [13]:
# 8. Identify duplicate Customer ID values and count how many duplicates exist. 
df["Customer ID"].duplicated().sum()
df[df["Customer ID"].duplicated()]

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
226,NaN,18,58188.80528,737.9284458,15.655950,12.0,3.330254,Chennai,Consumer,Female,Y,NaN,2022-03-18,Referral,normal
300,NaN,NaN,93665.74378,703.9692987,12.723292,7.0,NaN,Pune,SMB,Female,1,No,NaN,Email,follow-up needed
421,NaN,29.6 years,NaN,641.3441152,8.940646,5.0,3.687539,NaN,Consumer,Female,1,No,2021-12-05,Unknown,NaN
770,NaN,20.39545706,92366.06753,767.8048841,4.524943,3.0,4.358065,Mumbai,Enterprise,f,N,No,2021-09-05,???,NaN
821,NaN,46.41996378,81119.71831,597.3307848,1.076200,5.0,4.346306,Delhi,consumer,f,1,Yes,2022-12-26,Email,NaN
876,NaN,36.57634009,76629.87047,699.109735,4.977078,6.0,2.700057,Mumbai,consumer,M,N,Yes,2021-07-01,referral,good
993,NaN,47.54933612,NaN,NaN,0.693710,4.0,3.659781,NaN,Enterprise,NaN,NaN,No,2024-07-09,Referral,late payment
1023,NaN,NaN,34219.41505,NaN,3.779121,4.0,3.529211,Hyderabad,NaN,M,N,No,2023-07-05,Google Ads,ok
1188,NaN,28.97406958,NaN,744 pts,7.947965,8.0,2.379383,Hyderabad,Consumer,f,Yes,No,2026-06-06,NaN,urgent
1202,NaN,42.23152645,35310.77625,684.8618643,2.465432,6.0,4.979391,Delhi,SMB,m,1,No,2024-10-10,google_ads,late payment
1212,NaN,56.44358785,"$99,697",749.3298384,3.743193,6.0,NaN,NaN,NaN,M,Y,Yes,2024-07-18,WEB,NaN
1248,NaN,34.60645101,96811.19575,798.1150352,1.551247,5.0,3.288656,Mumbai,SMB.,M,N,No,2023-09-16,Social,follow-up needed
1338,NaN,26.5 years,"$89,682",692.0794813,1.877392,4.0,3.783551,Pune,Consumer,m,N,No,2023-12-04,WEB,NaN
1346,NaN,46.22898842,60122.78196,684.8548451,3.837557,2.0,4.267750,Mumbai,consumer,F,N,Yes,2023-01-01,referral,follow-up needed
1448,NaN,18,NaN,628.337014,7.137356,5.0,NaN,Pune,Enterprise,Female,no,NaN,2024-08-25,Google Ads,NaN
1451,NaN,47.20187446,28270.08329,549.3662455,3.019237,6.0,3.441021,Hyderabad,SMB,m,yes,Yes,2023-10-12,Unknown,good
1462,NaN,49.99203599,58348.28529,511.5806801,2.775352,NaN,NaN,Mumbai,SMB,Female,no,No,2024-07-07,NaN,NaN
1564,NaN,42.96550781,"$64,045",561 pts,4.549291,4.0,3.513904,Chennai,Consumer,m,No,No,03/08/2023,Email,NaN
1652,NaN,33.27510593,37475.10034,NaN,4.345689,11.0,-999.000000,Mumbai,SMB,f,NaN,NaN,2022-02-15,Social,ok

In [14]:
# 9. Remove duplicate customer records while keeping the first occurrence.  
df = df.drop_duplicates(keep = "first")
df

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.26951178,79436.89335,633.9740063,14.007477,NaN,3.556073,Bengaluru,Consumer,M,no,No,2024-02-26,email,normal
1996,CUST-01295,41.09168505,39912.37991,701.7201056,0.673289,8.0,2.963094,Pune,SMB,m,N,Yes,2024-08-11,Website,good
1997,CUST-00861,26.21576696,24522.26545,647.7993363,2.026485,12.0,3.079259,Hyderabad,SMB.,F,yes,No,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61056,521 pts,7.168156,5.0,3.579652,Hyderabad,SMB,NaN,N,Yes,2025-01-26,Email,ok
1999,CUST-01127,59.25609491,53723.87392,576.7390735,9.720663,NaN,1.100520,Pune,Consumer,NaN,yes,No,2024-02-22,???,good

In [15]:
# 10.Find all unique values in the customer_segment column and identify  inconsistent categories such as Consumer, consumer, consumer , etc.  
df["customer_segment"].value_counts()
df.rename(columns = {"Consumer":"consumer","SMB": "SMB."},inplace = True)
df["customer_segment"].value_counts()

customer_segment
Consumer      666
SMB           395
Enterprise    293
consumer      121
UNKNOWN        76
SMB.           69
Name: count, dtype: int64

In [16]:
# 11.Clean the customer_segment column by standardizing capitalization and  whitespace. 

df["customer_segment"] = df["customer_segment"].str.strip().str.title()
df.head()
#df["customer_segment"].unique()

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,Consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???

In [17]:
# 12.Find all unique values in the gender column and convert them into consistent  categories such as Male and Female.  
df["gender"].unique()
df["gender"] = df["gender"].str.strip().str.title()
df["gender"].unique()
df["gender"] = df["gender"].str.strip().str.upper().replace({
    "M": "Male",
    "F": "Female"
})
df["gender"]
df["gender"].unique()

array([nan, 'MALE', 'Male', 'FEMALE', 'Female'], dtype=object)

In [19]:
# 13.Clean the is_active column so values such as Yes, yes, Y, 1 become 1, and  No, no, N, 0 become 0. 
df["is_active"].unique()
df["is_active"] = df["is_active"].str.strip().str.upper().replace({
    "yes": "Yes",
    "Y":"Yes",
    "no": "NO",
    "1":"Yes",
    "0":"No",
    "N":"nan",
    "NAN":"nan"
    
})
df["is_active"].unique()

array(['YES', nan, 'nan', 'NO'], dtype=object)

In [25]:
# 14.Convert the churn_flag column from categorical values (Yes/No) into a binary  numerical column (1/0). 
df["churn_flag"] = df["churn_flag"].map({"Yes": 1, "No": 0})

df

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,Consumer,NaN,YES,NaN,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,MALE,NaN,NaN,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,Male,YES,NaN,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,Male,nan,NaN,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,MALE,YES,NaN,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.26951178,79436.89335,633.9740063,14.007477,NaN,3.556073,Bengaluru,Consumer,Male,NO,NaN,2024-02-26,email,normal
1996,CUST-01295,41.09168505,39912.37991,701.7201056,0.673289,8.0,2.963094,Pune,Smb,Male,nan,NaN,2024-08-11,Website,good
1997,CUST-00861,26.21576696,24522.26545,647.7993363,2.026485,12.0,3.079259,Hyderabad,Smb.,Female,YES,NaN,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61056,521 pts,7.168156,5.0,3.579652,Hyderabad,Smb,NaN,nan,NaN,2025-01-26,Email,ok
1999,CUST-01127,59.25609491,53723.87392,576.7390735,9.720663,NaN,1.100520,Pune,Consumer,NaN,YES,NaN,2024-02-22,???,good

In [26]:
# 15.Identify all values in income_usd that cannot be directly interpreted as  numbers.  
df.loc[pd.to_numeric(df['income_usd'], errors='coerce').isna(), 'income_usd'].unique()

array(['$44,696', '$41,941', nan, '$123,682', '$40,978', '$45,565',
       '$112,864', '$38,946', '$93,738', '$70,056', '$26,771', 'missing',
       '$48,959', '$36,410', '$86,520', '$88,847', '$88,960', '$50,211',
       '$104,630', '$72,142', '$34,864', '$130,837', '$90,730', '$29,657',
       '$60,407', '₹55k', '$506,709', '$71,214', '$191,997', '$35,341',
       '$171,139', '$65,761', '$30,152', '$47,631', '$319,924', '$46,216',
       '$49,366', '$78,703', '$44,955', '$76,860', '$50,094', '$129,799',
       '$32,702', '$33,399', '$19,760', '$146,497', '$30,746', '$107,324',
       '$19,808', 'error', '$49,885', '$22,575', '$53,462', '$100,254',
       '$37,397', '$89,920', '$60,643', '$153,576', '$114,703',
       '$117,570', '$155,204', '$39,065', '$108,002', '$33,428',
       '$18,612', '$32,495', '$31,099', '$60,008', '$31,588', '$84,034',
       '$92,205', '$30,921', '$38,009', '$61,792', '$48,656', '$49,855',
       '$23,569', '$38,605', '$37,860', '$47,580', '$24,527', '$78,202',
       '$53,993', '$64,415', 'not available', '$99,869', '$543,686',
       '$74,109', '$45,886', '$75,683', '$59,291', '$41,955', '$37,026',
       '$13,148', '$56,234', '$73,642', '$44,722', '$39,362', '$41,269',
       '$33,259', '$34,160', '$45,415', '$55,242', '$99,697', '$35,506',
       '$352,568', '$25,393', '$20,322', '$65,732', '$15,187', '$61,230',
       '$38,916', '$97,960', '$93,193', '$42,625', '$36,305', '$89,682',
       '$33,715', '$34,982', '$45,435', '$212,590', '$151,415', '$38,849',
       '$256,510', '$25,921', '$52,112', '$155,352', '$45,288', '$76,139',
       '$48,047', '$27,675', '$55,161', '$63,822', '$124,103', '$26,579',
       '$27,606', '$87,822', '$83,857', '$31,808', '$24,295', '$22,540',
       '$38,251', '$41,234', '$506,702', '$64,045', '$52,352', '$31,857',
       '$98,449', '$54,157', '$49,817', '$17,863', '$160,831', '$119,220',
       '$264,787', '$69,968', '$105,759', '$76,027', '$24,407',
       '$135,870', '$40,483', '$68,496', '$53,034', '$50,179', '$41,996',
       '$295,916', '$100,739', '$64,975', '$64,537', '$30,668', '$47,068',
       '$51,813', '$57,778', '$50,057', '$125,589', '$22,832', '$58,551',
       '$135,575', '$34,809', '$80,389', '$58,046'], dtype=object)