# Easy Level (1–10)

In [59]:
#1.Load the dataset and display the first 10 records.
import pandas as pd
df = pd.read_csv("C:/Users/anilr/Downloads/Bank_customer_churn.csv")
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [60]:
#2 Display the last 15 customers.
df.tail(15)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9985,9986,15586914,Nepean,659,France,Male,36,6,123841.49,2,1,0,96833.00,0
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9987,9988,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [61]:
# 3.Show 7 random customer records.
df.sample(7)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
4697,4698,15680706,Balashov,537,Germany,Male,48,4,131834.80,1,1,0,166476.95,1
2489,2490,15776824,Rossi,714,France,Male,28,6,122724.37,1,1,1,67057.27,0
9660,9661,15589401,Allen,550,France,Female,30,4,0.00,2,1,0,89216.29,0
2628,2629,15775891,Myers,634,Germany,Male,48,2,107247.69,1,1,1,103712.05,1
9851,9852,15792077,Degtyaryov,671,Germany,Male,28,8,119859.52,2,1,0,125422.66,0
3548,3549,15776827,Langdon,770,Germany,Male,37,5,141547.26,2,0,1,180326.83,0
4073,4074,15634143,Onyemauchechi,581,Spain,Male,30,0,53291.86,1,0,0,196582.28,0

In [62]:
# 4.Print complete dataset information and identify:
'''• Total columns
• Data type of each column
• Missing values'''
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [63]:
# 5.Find missing values in every column.
df.isna()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [64]:
#6.Display only numerical columns.
df.select_dtypes(include = ["int"]).columns

Index(['RowNumber', 'CustomerId', 'CreditScore', 'Age', 'Tenure',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'Exited'],
      dtype='object')

In [65]:
# 7.Generate the statistical summary of numerical columns.
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [66]:
# 8.Find duplicate rows and print how many exist.
df.duplicated().sum()

np.int64(0)

In [67]:
# 9.Remove duplicate rows and store the cleaned dataset.
df.drop_duplicates(inplace = True)
df.duplicated().sum()

np.int64(0)

In [68]:
#10.Count how many customers have exited and how many have not exited.
df["Exited"].value_counts(dropna = True)

Exited
0    7963
1    2037
Name: count, dtype: int64

# Medium Level (11–20)

In [69]:
# 11. Rename the following columns:
'''CustomerId → Customer_ID
CreditScore → Credit_Score
EstimatedSalary → Salary
Exited → Churn'''

df.rename(columns = {"CustomerId":"Customer_ID",
                       "CreditScore":"Credit_Score",
                       "EstimatedSalary":"Salary",
                       "Exited":"Churn"},inplace = True)
df

,RowNumber,Customer_ID,Surname,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Churn
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [70]:
# 12. Add the prefix
#Bank_to every column name.

df = df.add_prefix("Bank_")
df

,Bank_RowNumber,Bank_Customer_ID,Bank_Surname,Bank_Credit_Score,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_Salary,Bank_Churn
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [71]:
# 13.Convert the Age column into float datatype.
df["Age"] = df["Bank_Age"].astype(float)
df["Age"]

0       42.0
1       41.0
2       42.0
3       39.0
4       43.0
        ...
9995    39.0
9996    35.0
9997    36.0
9998    42.0
9999    28.0
Name: Age, Length: 10000, dtype: float64

In [72]:
# 14.Convert the Exited column into string datatype.
df["Bank_Churn"] = df["Bank_Churn"].astype(str)
df["Bank_Churn"]

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Bank_Churn, Length: 10000, dtype: object

In [73]:
# 15 Suppose the Balance column has missing values. Replace them using the mean of the Balance column.
Bank_Balance_mean =  df['Bank_Balance'].mean()
Bank_Balance_mean

np.float64(76485.889288)

In [74]:
#16 Suppose the Age column has missing values. Replace them using the median age.

Bank_Age_median =  df['Bank_Age'].median()
Bank_Age_median

37.0

In [75]:
# 17. Display only the first five rows after renaming the columns.
df.head(5)

,Bank_RowNumber,Bank_Customer_ID,Bank_Surname,Bank_Credit_Score,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_Salary,Bank_Churn,Age
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,42.0
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,41.0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,42.0
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,39.0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,43.0

In [76]:
# 18 Create a new DataFrame by dropping these columns:
"""RowNumber
   CustomerId
   Surname
Display the first 10 rows."""


df1 = df.drop("Bank_Customer_ID",axis = 1)
df2 = df1.drop("Bank_Credit_Score",axis = 1)
df3 = df2.drop("Bank_Surname",axis = 1)
df3

,Bank_RowNumber,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_Salary,Bank_Churn,Age
0,1,France,Female,42,2,0.00,1,1,1,101348.88,1,42.0
1,2,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,41.0
2,3,France,Female,42,8,159660.80,3,1,0,113931.57,1,42.0
3,4,France,Female,39,1,0.00,2,0,0,93826.63,0,39.0
4,5,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,43.0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,France,Male,39,5,0.00,2,1,0,96270.64,0,39.0
9996,9997,France,Male,35,10,57369.61,1,1,1,101699.77,0,35.0
9997,9998,France,Female,36,7,0.00,1,0,1,42085.58,1,36.0
9998,9999,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,42.0
9999,10000,France,Female,28,4,130142.79,1,1,0,38190.78,0,28.0

In [77]:
# 19.Drop the Geography column and display dataset information again.
df = pd.read_csv("C:/Users/anilr/Downloads/Bank_customer_churn.csv")
df.drop("Geography", axis=1, inplace=True)
df

,RowNumber,CustomerId,Surname,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,Female,28,4,130142.79,1,1,0,38190.78,0

In [78]:
# 20.Rename NumOfProducts to Products and HasCrCard to CreditCard.
df.rename(columns = {"NumOfProducts":"Products",
                       "HasCrCard":"CreditCard",
                       },inplace = True)
df

,RowNumber,CustomerId,Surname,CreditScore,Gender,Age,Tenure,Balance,Products,CreditCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,Female,28,4,130142.79,1,1,0,38190.78,0

# Hard Level (21–30)

In [79]:
#21 (Real Company Task)
'''Your manager wants cleaner column names.
Rename every column as follows:
RowNumber → Row_No
CustomerId → Customer_ID
Surname → Last_Name
CreditScore → Credit_Score
Geography → Country
Gender → Sex
EstimatedSalary → Salary
Exited → Target
Display the first five rows'''

df.rename(columns = {"RowNumber":"Row_No",
                       "CustomerId":"Customer_ID",
                     "Surname":"Last_Name",
                     "CreditScore":"Credit_Score",
                     "Gender":"Sex",
                     "EstimatedSalary":"Salary",
                     "Exited":"Target"
                       },inplace = True)
df

,Row_No,Customer_ID,Last_Name,Credit_Score,Sex,Age,Tenure,Balance,Products,CreditCard,IsActiveMember,Salary,Target
0,1,15634602,Hargrave,619,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,Female,28,4,130142.79,1,1,0,38190.78,0

In [80]:
# Q22 Create a new DataFrame that contains only numeric columns. Then generate its statistical summary.
df1 = df.select_dtypes(include = ["float","int"]).columns
df.describe()

,Row_No,Customer_ID,Credit_Score,Age,Tenure,Balance,Products,CreditCard,IsActiveMember,Salary,Target
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [81]:
# Q23 Your company received duplicate customer records.
'''Tasks:
• Count duplicates.
• Remove duplicates.
• Display dataset information after cleaning.'''
df=pd.read_csv("C:/Users/anilr/Downloads/dataset.csv") 
df.duplicated().sum()
df.drop_duplicates(inplace = True)
df
df.duplicated().sum()

np.int64(0)

In [104]:
# Q24 Management wants every column name to begin with Customer_  Apply this transformation using the appropriate method.
df = pd.read_csv("C:/Users/anilr/Downloads/Bank_customer_churn.csv")
df = df.add_prefix("Customer_")
df

,Customer_RowNumber,Customer_CustomerId,Customer_Surname,Customer_CreditScore,Customer_Geography,Customer_Gender,Customer_Age,Customer_Tenure,Customer_Balance,Customer_NumOfProducts,Customer_HasCrCard,Customer_IsActiveMember,Customer_EstimatedSalary,Customer_Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [105]:
# Q25 After renaming the columns, convert
"""Age
Balance
Salary
to float datatype.
Print dataset information."""
df.rename(columns = {"Customer_Age":"Age",
                        "Customer_Balance":"Balance",
                        "Customer_EstimatedSalary":"Salary"
                        },inplace = True)
df
df = df.select_dtypes(include = ["float"]).columns
df

Index(['Balance', 'Salary'], dtype='object')

In [204]:
# Q26  Assume CreditScore contains missing values.
#Replace them with the median CreditScore.
df = pd.read_csv("C:/Users/anilr/Downloads/Bank_customer_churn.csv")
(df.isnull().sum())

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [195]:
'''Q27
Assume EstimatedSalary contains missing values.
Replace them with the mean salary.
Then print the first eight rows.'''
df = pd.read_csv("C:/Users/anilr/Downloads/Bank_customer_churn.csv")

Customer_CreditScore_median =  df["CreditScore"].median()
print(Customer_CreditScore_median)
df.head(8)

652.0

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1

In [131]:
# Q28 (Data Cleaning Challenge)
#Perform all the following:
# Remove duplicate rows.
df.duplicated().sum()
print(df)
#• Rename Exited to Target.
df.rename(columns = {"Exited":"Target"},inplace = True)
print(df)
#• Convert Target to string.
df["Target"] = df["Target"].astype(str)
print(df)
#• Display dataset information.
df.info()
print(df)

      Customer_ID  Credit_Score Geography  Gender   Age  Tenure    Balance  \
0        15634602           619    France  Female  42.0       2       0.00
1        15647311           608     Spain  Female  41.0       1   83807.86
2        15619304           502    France  Female  42.0       8  159660.80
3        15701354           699    France  Female  39.0       1       0.00
4        15737888           850     Spain  Female  43.0       2  125510.82
...           ...           ...       ...     ...   ...     ...        ...
9995     15606229           771    France    Male  39.0       5       0.00
9996     15569892           516    France    Male  35.0      10   57369.61
9997     15584532           709    France  Female  36.0       7       0.00
9998     15682355           772   Germany    Male  42.0       3   75075.31
9999     15628319           792    France  Female  28.0       4  130142.79

      NumOfProducts  HasCrCard  IsActiveMember     Salary Target
0                 1          1               1  101348.88    1.0
1                 1          0               1  112542.58    0.0
2                 3          1               0  113931.57    1.0
3                 2          0               0   93826.63    0.0
4                 1          1               1   79084.10    0.0
...             ...        ...             ...        ...    ...
9995              2          1               0   96270.64    0.0
9996              1          1               1  101699.77    0.0
9997              1          0               1   42085.58    1.0
9998              2          1               0   92888.52    1.0
9999              1          1               0   38190.78    0.0

[10000 rows x 12 columns]
      Customer_ID  Credit_Score Geography  Gender   Age  Tenure    Balance  \
0        15634602           619    France  Female  42.0       2       0.00
1        15647311           608     Spain  Female  41.0       1   83807.86
2        15619304           502    France  Female  42.0       8  159660.80
3        15701354           699    France  Female  39.0       1       0.00
4        15737888           850     Spain  Female  43.0       2  125510.82
...           ...           ...       ...     ...   ...     ...        ...
9995     15606229           771    France    Male  39.0       5       0.00
9996     15569892           516    France    Male  35.0      10   57369.61
9997     15584532           709    France  Female  36.0       7       0.00
9998     15682355           772   Germany    Male  42.0       3   75075.31
9999     15628319           792    France  Female  28.0       4  130142.79

      NumOfProducts  HasCrCard  IsActiveMember     Salary Target
0                 1          1               1  101348.88    1.0
1                 1          0               1  112542.58    0.0
2                 3          1               0  113931.57    1.0
3                 2          0               0   93826.63    0.0
4                 1          1               1   79084.10    0.0
...             ...        ...             ...        ...    ...
9995              2          1               0   96270.64    0.0
9996              1          1               1  101699.77    0.0
9997              1          0               1   42085.58    1.0
9998              2          1               0   92888.52    1.0
9999              1          1               0   38190.78    0.0

[10000 rows x 12 columns]
      Customer_ID  Credit_Score Geography  Gender   Age  Tenure    Balance  \
0        15634602           619    France  Female  42.0       2       0.00
1        15647311           608     Spain  Female  41.0       1   83807.86
2        15619304           502    France  Female  42.0       8  159660.80
3        15701354           699    France  Female  39.0       1       0.00
4        15737888           850     Spain  Female  43.0       2  125510.82
...           ...           ...       ...     ...   ...     ...        ...
9995     15606229           771    France    Male  39.0       5       0.00
9996     15569892           516    France    Male  35.0      10   57369.61
9997     15584532           709    France  Female  36.0       7       0.00
9998     15682355           772   Germany    Male  42.0       3   75075.31
9999     15628319           792    France  Female  28.0       4  130142.79

      NumOfProducts  HasCrCard  IsActiveMember     Salary Target
0                 1          1               1  101348.88    1.0
1                 1          0               1  112542.58    0.0
2                 3          1               0  113931.57    1.0
3                 2          0               0   93826.63    0.0
4                 1          1               1   79084.10    0.0
...             ...        ...             ...        ...    ...
9995              2          1               0   96270.64    0.0
9996              1          1               1  101699.77    0.0
9997              1          0               1   42085.58    1.0
9998              2          1               0   92888.52    1.0
9999              1          1               0   38190.78    0.0

[10000 rows x 12 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer_ID     10000 non-null  int64
 1   Credit_Score    10000 non-null  int64
 2   Geography       10000 non-null  object
 3   Gender          10000 non-null  object
 4   Age             10000 non-null  float64
 5   Tenure          10000 non-null  int64
 6   Balance         10000 non-null  float64
 7   NumOfProducts   10000 non-null  int64
 8   HasCrCard       10000 non-null  int64
 9   IsActiveMember  10000 non-null  int64
 10  Salary          10000 non-null  float64
 11  Target          10000 non-null  object
dtypes: float64(3), int64(6), object(3)
memory usage: 937.6+ KB
      Customer_ID  Credit_Score Geography  Gender   Age  Tenure    Balance  \
0        15634602           619    France  Female  42.0       2       0.00
1        15647311           608     Spain  Female  41.0       1   83807.86
2        15619304           502    France  Female  42.0       8  159660.80
3        15701354           699    France  Female  39.0       1       0.00
4        15737888           850     Spain  Female  43.0       2  125510.82
...           ...           ...       ...     ...   ...     ...        ...
9995     15606229           771    France    Male  39.0       5       0.00
9996     15569892           516    France    Male  35.0      10   57369.61
9997     15584532           709    France  Female  36.0       7       0.00
9998     15682355           772   Germany    Male  42.0       3   75075.31
9999     15628319           792    France  Female  28.0       4  130142.79

      NumOfProducts  HasCrCard  IsActiveMember     Salary Target
0                 1          1               1  101348.88    1.0
1                 1          0               1  112542.58    0.0
2                 3          1               0  113931.57    1.0
3                 2          0               0   93826.63    0.0
4                 1          1               1   79084.10    0.0
...             ...        ...             ...        ...    ...
9995              2          1               0   96270.64    0.0
9996              1          1               1  101699.77    0.0
9997              1          0               1   42085.58    1.0
9998              2          1               0   92888.52    1.0
9999              1          1               0   38190.78    0.0

[10000 rows x 12 columns]

In [197]:
# Q29 (Transformation Challenge)
#Create a copy of the dataset.
df1 = df
#Perform these transformations:
#• Rename Gender to CustomerGender
#• Rename Geography to Country
df.rename(columns = {"CustomerId":"Customer_ID",
                     "CreditScore":"Credit_Score"
                    },inplace = True)
print(df)
#• Add prefix Bank_
df.add_prefix("Bank_")
print(df)
#• Remove RowNumber
df = df.drop("RowNumber",axis = 1)
print(df)
#• Display first 10 rows
df.head(10)
print(df)

      RowNumber  Customer_ID    Surname  Credit_Score Geography  Gender  Age  \
0             1     15634602   Hargrave           619    France  Female   42
1             2     15647311       Hill           608     Spain  Female   41
2             3     15619304       Onio           502    France  Female   42
3             4     15701354       Boni           699    France  Female   39
4             5     15737888   Mitchell           850     Spain  Female   43
...         ...          ...        ...           ...       ...     ...  ...
9995       9996     15606229   Obijiaku           771    France    Male   39
9996       9997     15569892  Johnstone           516    France    Male   35
9997       9998     15584532        Liu           709    France  Female   36
9998       9999     15682355  Sabbatini           772   Germany    Male   42
9999      10000     15628319     Walker           792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1
1          1   83807.86              1          0               1
2          8  159660.80              3          1               0
3          1       0.00              2          0               0
4          2  125510.82              1          1               1
...      ...        ...            ...        ...             ...
9995       5       0.00              2          1               0
9996      10   57369.61              1          1               1
9997       7       0.00              1          0               1
9998       3   75075.31              2          1               0
9999       4  130142.79              1          1               0

      EstimatedSalary  Exited
0           101348.88       1
1           112542.58       0
2           113931.57       1
3            93826.63       0
4            79084.10       0
...               ...     ...
9995         96270.64       0
9996        101699.77       0
9997         42085.58       1
9998         92888.52       1
9999         38190.78       0

[10000 rows x 14 columns]
      RowNumber  Customer_ID    Surname  Credit_Score Geography  Gender  Age  \
0             1     15634602   Hargrave           619    France  Female   42
1             2     15647311       Hill           608     Spain  Female   41
2             3     15619304       Onio           502    France  Female   42
3             4     15701354       Boni           699    France  Female   39
4             5     15737888   Mitchell           850     Spain  Female   43
...         ...          ...        ...           ...       ...     ...  ...
9995       9996     15606229   Obijiaku           771    France    Male   39
9996       9997     15569892  Johnstone           516    France    Male   35
9997       9998     15584532        Liu           709    France  Female   36
9998       9999     15682355  Sabbatini           772   Germany    Male   42
9999      10000     15628319     Walker           792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1
1          1   83807.86              1          0               1
2          8  159660.80              3          1               0
3          1       0.00              2          0               0
4          2  125510.82              1          1               1
...      ...        ...            ...        ...             ...
9995       5       0.00              2          1               0
9996      10   57369.61              1          1               1
9997       7       0.00              1          0               1
9998       3   75075.31              2          1               0
9999       4  130142.79              1          1               0

      EstimatedSalary  Exited
0           101348.88       1
1           112542.58       0
2           113931.57       1
3            93826.63       0
4            79084.10       0
...               ...     ...
9995         96270.64       0
9996        101699.77       0
9997         42085.58       1
9998         92888.52       1
9999         38190.78       0

[10000 rows x 14 columns]
      Customer_ID    Surname  Credit_Score Geography  Gender  Age  Tenure  \
0        15634602   Hargrave           619    France  Female   42       2
1        15647311       Hill           608     Spain  Female   41       1
2        15619304       Onio           502    France  Female   42       8
3        15701354       Boni           699    France  Female   39       1
4        15737888   Mitchell           850     Spain  Female   43       2
...           ...        ...           ...       ...     ...  ...     ...
9995     15606229   Obijiaku           771    France    Male   39       5
9996     15569892  Johnstone           516    France    Male   35      10
9997     15584532        Liu           709    France  Female   36       7
9998     15682355  Sabbatini           772   Germany    Male   42       3
9999     15628319     Walker           792    France  Female   28       4

        Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0          0.00              1          1               1        101348.88
1      83807.86              1          0               1        112542.58
2     159660.80              3          1               0        113931.57
3          0.00              2          0               0         93826.63
4     125510.82              1          1               1         79084.10
...         ...            ...        ...             ...              ...
9995       0.00              2          1               0         96270.64
9996   57369.61              1          1               1        101699.77
9997       0.00              1          0               1         42085.58
9998   75075.31              2          1               0         92888.52
9999  130142.79              1          1               0         38190.78

      Exited
0          1
1          0
2          1
3          0
4          0
...      ...
9995       0
9996       0
9997       1
9998       1
9999       0

[10000 rows x 13 columns]
      Customer_ID    Surname  Credit_Score Geography  Gender  Age  Tenure  \
0        15634602   Hargrave           619    France  Female   42       2
1        15647311       Hill           608     Spain  Female   41       1
2        15619304       Onio           502    France  Female   42       8
3        15701354       Boni           699    France  Female   39       1
4        15737888   Mitchell           850     Spain  Female   43       2
...           ...        ...           ...       ...     ...  ...     ...
9995     15606229   Obijiaku           771    France    Male   39       5
9996     15569892  Johnstone           516    France    Male   35      10
9997     15584532        Liu           709    France  Female   36       7
9998     15682355  Sabbatini           772   Germany    Male   42       3
9999     15628319     Walker           792    France  Female   28       4

        Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0          0.00              1          1               1        101348.88
1      83807.86              1          0               1        112542.58
2     159660.80              3          1               0        113931.57
3          0.00              2          0               0         93826.63
4     125510.82              1          1               1         79084.10
...         ...            ...        ...             ...              ...
9995       0.00              2          1               0         96270.64
9996   57369.61              1          1               1        101699.77
9997       0.00              1          0               1         42085.58
9998   75075.31              2          1               0         92888.52
9999  130142.79              1          1               0         38190.78

      Exited
0          1
1          0
2          1
3          0
4          0
...      ...
9995       0
9996       0
9997       1
9998       1
9999       0

[10000 rows x 13 columns]

In [125]:
#Q30 Real Industry Mini Project
"""Your manager asks you to prepare a cleaned dataset for the Machine Learning team.
Perform all of these steps:
1. Load the dataset.
2. Display dataset information.
3. Check missing values.
4. Remove duplicate rows.
5. Rename the following columns:
o CustomerId → Customer_ID
o CreditScore → Credit_Score
o EstimatedSalary → Salary
o Exited → Target
6. Convert:
o Age → float
o Balance → float
o Target → string
7. Replace missing values:
o Age → median
o Balance → mean
8. Remove:
o RowNumber
o Surname
9. Display:
o First 10 rows
o Statistical summary
o Value counts of Target
o Final dataset information"""

# 1. Load the dataset.
df = pd.read_csv("C:/Users/anilr/Downloads/Bank_customer_churn.csv")
print(df)

# 2. Display dataset information.
df.info()
print(df)

# 3. Check missing values.
df.isnull().sum()
print(df)
# 4. Remove duplicate rows.
df.duplicated().sum()
print(df)

# 5. Rename the following columns:
#o CustomerId → Customer_ID
#o CreditScore → Credit_Score
#o EstimatedSalary → Salary
#o Exited → Target
df.rename(columns = {"CustomerId":"Customer_ID",
                          "CreditScore":"Credit_Score",
                          "EstimatedSalary":"Salary",
                          "Exited":"Target",
                         },inplace = True)
print(df)

#6. Convert:
#o Age → float
df["Age"] = df["Age"].astype(float)
print(df["Age"])
#o Balance → float
df["Balance"] = df["Balance"].astype(float)
print(df["Balance"])
#o Target → string
df["Target"] = df["Target"].astype(float)
print(df["Target"])

# 7. Replace missing values:
#o Age → median
Age_median =  df["Age"].median()
print(Age_median)
#o Balance → mean
Balance_median =  df["Balance"].mean()
print(Balance_median)

#8. Remove:
#o RowNumber
df.drop("RowNumber", axis=1, inplace=True)
print(df)
#o Surname
df.drop("Surname", axis=1, inplace=True)
print(df)

#9. Display:
#o First 10 rows
df.head(10)
print(df)
#o Statistical summary
df.head(10)
print(df)
#o Value counts of Target
df["Target"].value_counts()
print(df)
#o Final dataset information
df.info()
print(df)

      RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42
1             2    15647311       Hill          608     Spain  Female   41
2             3    15619304       Onio          502    France  Female   42
3             4    15701354       Boni          699    France  Female   39
4             5    15737888   Mitchell          850     Spain  Female   43
...         ...         ...        ...          ...       ...     ...  ...
9995       9996    15606229   Obijiaku          771    France    Male   39
9996       9997    15569892  Johnstone          516    France    Male   35
9997       9998    15584532        Liu          709    France  Female   36
9998       9999    15682355  Sabbatini          772   Germany    Male   42
9999      10000    15628319     Walker          792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1
1          1   83807.86              1          0               1
2          8  159660.80              3          1               0
3          1       0.00              2          0               0
4          2  125510.82              1          1               1
...      ...        ...            ...        ...             ...
9995       5       0.00              2          1               0
9996      10   57369.61              1          1               1
9997       7       0.00              1          0               1
9998       3   75075.31              2          1               0
9999       4  130142.79              1          1               0

      EstimatedSalary  Exited
0           101348.88       1
1           112542.58       0
2           113931.57       1
3            93826.63       0
4            79084.10       0
...               ...     ...
9995         96270.64       0
9996        101699.77       0
9997         42085.58       1
9998         92888.52       1
9999         38190.78       0

[10000 rows x 14 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB
      RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42
1             2    15647311       Hill          608     Spain  Female   41
2             3    15619304       Onio          502    France  Female   42
3             4    15701354       Boni          699    France  Female   39
4             5    15737888   Mitchell          850     Spain  Female   43
...         ...         ...        ...          ...       ...     ...  ...
9995       9996    15606229   Obijiaku          771    France    Male   39
9996       9997    15569892  Johnstone          516    France    Male   35
9997       9998    15584532        Liu          709    France  Female   36
9998       9999    15682355  Sabbatini          772   Germany    Male   42
9999      10000    15628319     Walker          792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1
1          1   83807.86              1          0               1
2          8  159660.80              3          1               0
3          1       0.00              2          0               0
4          2  125510.82              1          1               1
...      ...        ...            ...        ...             ...
9995       5       0.00              2          1               0
9996      10   57369.61              1          1               1
9997       7       0.00              1          0               1
9998       3   75075.31              2          1               0
9999       4  130142.79              1          1               0

      EstimatedSalary  Exited
0           101348.88       1
1           112542.58       0
2           113931.57       1
3            93826.63       0
4            79084.10       0
...               ...     ...
9995         96270.64       0
9996        101699.77       0
9997         42085.58       1
9998         92888.52       1
9999         38190.78       0

[10000 rows x 14 columns]
      RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42
1             2    15647311       Hill          608     Spain  Female   41
2             3    15619304       Onio          502    France  Female   42
3             4    15701354       Boni          699    France  Female   39
4             5    15737888   Mitchell          850     Spain  Female   43
...         ...         ...        ...          ...       ...     ...  ...
9995       9996    15606229   Obijiaku          771    France    Male   39
9996       9997    15569892  Johnstone          516    France    Male   35
9997       9998    15584532        Liu          709    France  Female   36
9998       9999    15682355  Sabbatini          772   Germany    Male   42
9999      10000    15628319     Walker          792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1
1          1   83807.86              1          0               1
2          8  159660.80              3          1               0
3          1       0.00              2          0               0
4          2  125510.82              1          1               1
...      ...        ...            ...        ...             ...
9995       5       0.00              2          1               0
9996      10   57369.61              1          1               1
9997       7       0.00              1          0               1
9998       3   75075.31              2          1               0
9999       4  130142.79              1          1               0

      EstimatedSalary  Exited
0           101348.88       1
1           112542.58       0
2           113931.57       1
3            93826.63       0
4            79084.10       0
...               ...     ...
9995         96270.64       0
9996        101699.77       0
9997         42085.58       1
9998         92888.52       1
9999         38190.78       0

[10000 rows x 14 columns]
      RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42
1             2    15647311       Hill          608     Spain  Female   41
2             3    15619304       Onio          502    France  Female   42
3             4    15701354       Boni          699    France  Female   39
4             5    15737888   Mitchell          850     Spain  Female   43
...         ...         ...        ...          ...       ...     ...  ...
9995       9996    15606229   Obijiaku          771    France    Male   39
9996       9997    15569892  Johnstone          516    France    Male   35
9997       9998    15584532        Liu          709    France  Female   36
9998       9999    15682355  Sabbatini          772   Germany    Male   42
9999      10000    15628319     Walker          792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1
1          1   83807.86              1          0               1
2          8  159660.80              3          1               0
3          1       0.00              2          0               0
4          2  125510.82              1          1               1
...      ...        ...            ...        ...             ...
9995       5       0.00              2          1               0
9996      10   57369.61              1          1               1
9997       7       0.00              1          0               1
9998       3   75075.31              2          1               0
9999       4  130142.79              1          1               0

      EstimatedSalary  Exited
0           101348.88       1
1           112542.58       0
2           113931.57       1
3            93826.63       0
4            79084.10       0
...               ...     ...
9995         96270.64       0
9996        101699.77       0
9997         42085.58       1
9998         92888.52       1
9999         38190.78       0

[10000 rows x 14 columns]
      RowNumber  Customer_ID    Surname  Credit_Score Geography  Gender  Age  \
0             1     15634602   Hargrave           619    France  Female   42
1             2     15647311       Hill           608     Spain  Female   41
2             3     15619304       Onio           502    France  Female   42
3             4     15701354       Boni           699    France  Female   39
4             5     15737888   Mitchell           850     Spain  Female   43
...         ...          ...        ...           ...       ...     ...  ...
9995       9996     15606229   Obijiaku           771    France    Male   39
9996       9997     15569892  Johnstone           516    France    Male   35
9997       9998     15584532        Liu           709    France  Female   36
9998       9999     15682355  Sabbatini           772   Germany    Male   42
9999      10000     15628319     Walker           792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember     Salary  \
0          2       0.00              1          1               1  101348.88
1          1   83807.86              1          0               1  112542.58
2          8  159660.80              3          1               0  113931.57
3          1       0.00              2          0               0   93826.63
4          2  125510.82              1          1               1   79084.10
...      ...        ...            ...        ...             ...        ...
9995       5       0.00              2          1               0   96270.64
9996      10   57369.61              1          1               1  101699.77
9997       7       0.00              1          0               1   42085.58
9998       3   75075.31              2          1               0   92888.52
9999       4  130142.79              1          1               0   38190.78

      Target
0          1
1          0
2          1
3          0
4          0
...      ...
9995       0
9996       0
9997       1
9998       1
9999       0

[10000 rows x 14 columns]
0       42.0
1       41.0
2       42.0
3       39.0
4       43.0
        ...
9995    39.0
9996    35.0
9997    36.0
9998    42.0
9999    28.0
Name: Age, Length: 10000, dtype: float64
0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Balance, Length: 10000, dtype: float64
0       1.0
1       0.0
2       1.0
3       0.0
4       0.0
       ...
9995    0.0
9996    0.0
9997    1.0
9998    1.0
9999    0.0
Name: Target, Length: 10000, dtype: float64
37.0
76485.889288
      Customer_ID    Surname  Credit_Score Geography  Gender   Age  Tenure  \
0        15634602   Hargrave           619    France  Female  42.0       2
1        15647311       Hill           608     Spain  Female  41.0       1
2        15619304       Onio           502    France  Female  42.0       8
3        15701354       Boni           699    France  Female  39.0       1
4        15737888   Mitchell           850     Spain  Female  43.0       2
...           ...        ...           ...       ...     ...   ...     ...
9995     15606229   Obijiaku           771    France    Male  39.0       5
9996     15569892  Johnstone           516    France    Male  35.0      10
9997     15584532        Liu           709    France  Female  36.0       7
9998     15682355  Sabbatini           772   Germany    Male  42.0       3
9999     15628319     Walker           792    France  Female  28.0       4

        Balance  NumOfProducts  HasCrCard  IsActiveMember     Salary  Target
0          0.00              1          1               1  101348.88     1.0
1      83807.86              1          0               1  112542.58     0.0
2     159660.80              3          1               0  113931.57     1.0
3          0.00              2          0               0   93826.63     0.0
4     125510.82              1          1               1   79084.10     0.0
...         ...            ...        ...             ...        ...     ...
9995       0.00              2          1               0   96270.64     0.0
9996   57369.61              1          1               1  101699.77     0.0
9997       0.00              1          0               1   42085.58     1.0
9998   75075.31              2          1               0   92888.52     1.0
9999  130142.79              1          1               0   38190.78     0.0

[10000 rows x 13 columns]
      Customer_ID  Credit_Score Geography  Gender   Age  Tenure    Balance  \
0        15634602           619    France  Female  42.0       2       0.00
1        15647311           608     Spain  Female  41.0       1   83807.86
2        15619304           502    France  Female  42.0       8  159660.80
3        15701354           699    France  Female  39.0       1       0.00
4        15737888           850     Spain  Female  43.0       2  125510.82
...           ...           ...       ...     ...   ...     ...        ...
9995     15606229           771    France    Male  39.0       5       0.00
9996     15569892           516    France    Male  35.0      10   57369.61
9997     15584532           709    France  Female  36.0       7       0.00
9998     15682355           772   Germany    Male  42.0       3   75075.31
9999     15628319           792    France  Female  28.0       4  130142.79

      NumOfProducts  HasCrCard  IsActiveMember     Salary  Target
0                 1          1               1  101348.88     1.0
1                 1          0               1  112542.58     0.0
2                 3          1               0  113931.57     1.0
3                 2          0               0   93826.63     0.0
4                 1          1               1   79084.10     0.0
...             ...        ...             ...        ...     ...
9995              2          1               0   96270.64     0.0
9996              1          1               1  101699.77     0.0
9997              1          0               1   42085.58     1.0
9998              2          1               0   92888.52     1.0
9999              1          1               0   38190.78     0.0

[10000 rows x 12 columns]
      Customer_ID  Credit_Score Geography  Gender   Age  Tenure    Balance  \
0        15634602           619    France  Female  42.0       2       0.00
1        15647311           608     Spain  Female  41.0       1   83807.86
2        15619304           502    France  Female  42.0       8  159660.80
3        15701354           699    France  Female  39.0       1       0.00
4        15737888           850     Spain  Female  43.0       2  125510.82
...           ...           ...       ...     ...   ...     ...        ...
9995     15606229           771    France    Male  39.0       5       0.00
9996     15569892           516    France    Male  35.0      10   57369.61
9997     15584532           709    France  Female  36.0       7       0.00
9998     15682355           772   Germany    Male  42.0       3   75075.31
9999     15628319           792    France  Female  28.0       4  130142.79

      NumOfProducts  HasCrCard  IsActiveMember     Salary  Target
0                 1          1               1  101348.88     1.0
1                 1          0               1  112542.58     0.0
2                 3          1               0  113931.57     1.0
3                 2          0               0   93826.63     0.0
4                 1          1               1   79084.10     0.0
...             ...        ...             ...        ...     ...
9995              2          1               0   96270.64     0.0
9996              1          1               1  101699.77     0.0
9997              1          0               1   42085.58     1.0
9998              2          1               0   92888.52     1.0
9999              1          1               0   38190.78     0.0

[10000 rows x 12 columns]
      Customer_ID  Credit_Score Geography  Gender   Age  Tenure    Balance  \
0        15634602           619    France  Female  42.0       2       0.00
1        15647311           608     Spain  Female  41.0       1   83807.86
2        15619304           502    France  Female  42.0       8  159660.80
3        15701354           699    France  Female  39.0       1       0.00
4        15737888           850     Spain  Female  43.0       2  125510.82
...           ...           ...       ...     ...   ...     ...        ...
9995     15606229           771    France    Male  39.0       5       0.00
9996     15569892           516    France    Male  35.0      10   57369.61
9997     15584532           709    France  Female  36.0       7       0.00
9998     15682355           772   Germany    Male  42.0       3   75075.31
9999     15628319           792    France  Female  28.0       4  130142.79

      NumOfProducts  HasCrCard  IsActiveMember     Salary  Target
0                 1          1               1  101348.88     1.0
1                 1          0               1  112542.58     0.0
2                 3          1               0  113931.57     1.0
3                 2          0               0   93826.63     0.0
4                 1          1               1   79084.10     0.0
...             ...        ...             ...        ...     ...
9995              2          1               0   96270.64     0.0
9996              1          1               1  101699.77     0.0
9997              1          0               1   42085.58     1.0
9998              2          1               0   92888.52     1.0
9999              1          1               0   38190.78     0.0

[10000 rows x 12 columns]
      Customer_ID  Credit_Score Geography  Gender   Age  Tenure    Balance  \
0        15634602           619    France  Female  42.0       2       0.00
1        15647311           608     Spain  Female  41.0       1   83807.86
2        15619304           502    France  Female  42.0       8  159660.80
3        15701354           699    France  Female  39.0       1       0.00
4        15737888           850     Spain  Female  43.0       2  125510.82
...           ...           ...       ...     ...   ...     ...        ...
9995     15606229           771    France    Male  39.0       5       0.00
9996     15569892           516    France    Male  35.0      10   57369.61
9997     15584532           709    France  Female  36.0       7       0.00
9998     15682355           772   Germany    Male  42.0       3   75075.31
9999     15628319           792    France  Female  28.0       4  130142.79

      NumOfProducts  HasCrCard  IsActiveMember     Salary  Target
0                 1          1               1  101348.88     1.0

# Bonus Challenge (Create New Columns)

# These require creating new columns using basic Pandas assignment along with the methods you've learned.

In [138]:
#B1
#Create a new column:
#TotalMoney = Balance + EstimatedSalary
df = pd.read_csv("C:/Users/anilr/Downloads/Bank_customer_churn.csv")
df["TotalMoney"] = df["Balance"] + df["EstimatedSalary"]
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,TotalMoney
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,101348.88
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,196350.44
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,273592.37
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,93826.63
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,204594.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,96270.64
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,159069.38
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,42085.58
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,167963.83
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,168333.57

In [164]:
#B2
#Create a new column:
#DoubleScore = CreditScore × 2
df = pd.read_csv("C:/Users/anilr/Downloads/Bank_customer_churn.csv")

df["DoubleScore"] = df["CreditScore"] * 2
df["DoubleScore"]

0       1238
1       1216
2       1004
3       1398
4       1700
        ...
9995    1542
9996    1032
9997    1418
9998    1544
9999    1584
Name: DoubleScore, Length: 10000, dtype: int64

In [160]:
# B3
#Create a new column:
#AgeAfter10Years = Age + 10
df["AgeAfter10Years"] = df["Age"] + 10
df["AgeAfter10Years"]

0       52
1       51
2       52
3       49
4       53
        ..
9995    49
9996    45
9997    46
9998    52
9999    38
Name: AgeAfter10Years, Length: 10000, dtype: int64

In [189]:
# B4
#Create a new column:
df["HasBalance"] = df["Balance"]
print(df["HasBalance"])
#HasBalance = Balance
mean_balance = df["HasBalance"].mean()
Balance = (int(mean_balance))
print(Balance)
#Replace missing values in this new column using the mean.

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: HasBalance, Length: 10000, dtype: float64
76485

In [168]:
#B5
#Create a new column:
#SalaryInLakhs = EstimatedSalary / 100000
df = pd.read_csv("C:/Users/anilr/Downloads/Bank_customer_churn.csv")
df["SalaryInLakhs"] = df["EstimatedSalary"] /100000
df["SalaryInLakhs"]

0       1.013489
1       1.125426
2       1.139316
3       0.938266
4       0.790841
          ...
9995    0.962706
9996    1.016998
9997    0.420856
9998    0.928885
9999    0.381908
Name: SalaryInLakhs, Length: 10000, dtype: float64

In [165]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,DoubleScore
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1238
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,1216
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1004
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,1398
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,1700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,1542
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,1032
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,1418
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,1544
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,1584