# Pandas Method Task: Bank Customer Churn Dataset

In [ ]:
"""• Use only:
o pd.read_csv()
o head()
o tail()
o sample()
o shape
o info()
o columns
o dtypes
o isnull()
o isna()
o Column selection (df["col"], df[["col1","col2"]])
o select_dtypes()
o describe()
o duplicated()
o drop_duplicates()
o value_counts()

"""

In [37]:
# 1. Load the dataset using the appropriate Pandas method and store it in a variable named df.

import pandas as pd
df = pd.read_csv("C:/Users/anilr/Downloads/Bank_customer_churn.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [5]:
# 2. Display the first 8 rows of the dataset.
df.head(8)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1

In [8]:
#3. Display the last 12 rows of the dataset.
df.tail(12)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [12]:
# 4. Show 10 random rows from the dataset.
df.sample(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
218,219,15659366,Shih,807,France,Male,43,1,105799.32,2,1,0,34888.04,1
5724,5725,15784286,Wood,641,Spain,Male,40,5,102145.13,1,1,1,100637.07,0
3658,3659,15661903,Hsia,699,France,Female,43,3,80764.03,1,1,0,199378.58,1
6330,6331,15715117,Peel,744,France,Female,39,6,0.00,1,0,0,10662.58,0
4223,4224,15588090,Ferri,726,Germany,Female,51,8,107494.86,2,1,0,140937.91,1
1768,1769,15770525,T'an,760,Spain,Male,28,1,141038.57,2,0,0,16287.38,0
8035,8036,15733705,Bull,577,France,Female,30,8,92472.10,2,0,1,126434.61,0
4516,4517,15812210,Yashina,497,Germany,Female,32,8,111537.23,4,1,1,9497.99,1
8689,8690,15684769,Whitson,542,France,Male,67,10,129431.36,1,0,1,21343.74,0
2067,2068,15767794,Browne,744,France,Male,31,9,120718.28,1,1,1,58961.49,0

In [15]:
# 5. Find the shape of the dataset.
#o How many rows are there?
#o How many columns are there?
df.shape
#10000 rows
# 14 columns

(10000, 14)

In [17]:
# 6. Display complete information about the dataset using one method.
#o Number of non-null values
#o Data types
#o Memory usage
df.info()
# Data types = int64,object,float64
# Memory usage = 1.1+

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [19]:
# 7. Print the names of all columns in the dataset.
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [21]:
# 8. Find the data type of every column. 
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [23]:
# 9. Check for missing values in every column using:
# o isnull().sum()
# o isna().sum()
df.isnull().sum()
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [24]:
# 10.Select only one column:
# o CreditScore
df["CreditScore"]

0       619
1       608
2       502
3       699
4       850
       ...
9995    771
9996    516
9997    709
9998    772
9999    792
Name: CreditScore, Length: 10000, dtype: int64

In [26]:
#11.Select the following multiple columns:
#o CustomerId
#o Surname
#o Balance
#o Exited
df[["CustomerId","Surname","Balance","Exited"]]

      CustomerId    Surname    Balance  Exited
0       15634602   Hargrave       0.00       1
1       15647311       Hill   83807.86       0
2       15619304       Onio  159660.80       1
3       15701354       Boni       0.00       0
4       15737888   Mitchell  125510.82       0
...          ...        ...        ...     ...
9995    15606229   Obijiaku       0.00       0
9996    15569892  Johnstone   57369.61       0
9997    15584532        Liu       0.00       1
9998    15682355  Sabbatini   75075.31       1
9999    15628319     Walker  130142.79       0

[10000 rows x 4 columns]

In [29]:
#12.Display only numeric columns using select_dtypes().
df.select_dtypes("int64")

,RowNumber,CustomerId,CreditScore,Age,Tenure,NumOfProducts,HasCrCard,IsActiveMember,Exited
0,1,15634602,619,42,2,1,1,1,1
1,2,15647311,608,41,1,1,0,1,0
2,3,15619304,502,42,8,3,1,0,1
3,4,15701354,699,39,1,2,0,0,0
4,5,15737888,850,43,2,1,1,1,0
...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,2,1,0,0
9996,9997,15569892,516,35,10,1,1,1,0
9997,9998,15584532,709,36,7,1,0,1,1
9998,9999,15682355,772,42,3,2,1,0,1
9999,10000,15628319,792,28,4,1,1,0,0

In [30]:
#13.Generate the statistical summary of all numeric columns using describe().
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [33]:
#14.Check for duplicate() rows in the dataset.
#o How many duplicate rows exist?
#o Remove all duplicate rows.
df.duplicated().sum()

np.int64(0)

In [35]:
# 15.Count the number of customers in each class of the Exited column using value_counts().
df.value_counts().sum()

np.int64(10000)

# Operators + Loops (1-5)

In [42]:
# 1. Take two numbers from user. Perform all arithmetic operations and also check which number is greater using comparison operators.
num1 = int(input())
num2 = int(input())
operations = ["Addition", "Subtraction", "Multiplication","Division", "Modulus", "Floor Division", "Exponentiation"]
for op in operations:
    if op == "Addition":
        print(f"Addition :{num1+num2}")
    elif op == "Subtraction":
        print(f"Subtraction :{num1-num2}")
    elif op == "Multiplication":
        print(f"Multiplication :{num1*num2}")
    elif op == "Division":
        print(f"Division :{num1/num2}")
    elif op == "Modulus":
        print(f"Modulus :{num1%num2}")
    elif op == "Floor Division":
        print(f"Floor Division {num1//num2}")
    else:
        print(f"Exponentiation {num1**num2}")

 10
 10

Addition :20
Subtraction :0
Multiplication :100
Division :1.0
Modulus :0
Floor Division 1
Exponentiation 10000000000

In [53]:
# 2. Print all numbers from 1 to 50. Skip multiples of 5 using continue and stop completely when number 40 is reached using break.
for i in range(1,51):
    if i % 5 == 0:
        print(i)
        if i >= 40:
            break

5
10
15
20
25
30
35
40

In [62]:
# 3. Take numbers from user until they enter negative number. Calculate sum and average using while loop.

sum = 0
count = 0
num = int(input())
while True:
    num = int(input())
    if num < 0:
        break
    sum+= num
    count += 1
if count>0:
    avg = sum /count
    print(avg)
    print(sum)
else:
    print("you are enter the -'ve number")

 10
 10
 10
 10
 -8

10.0
30

In [72]:
# 4. Print the following pattern using nested loops:
'''*****
****
***
**
*'''
for i in range(5,0,-1):
    
    for j in range(i):
        print("*",end=" ")
    print()

* * * * *
* * * *
* * *
* *
*

In [76]:
# 5. Find the factorial of a number using for loop and also using while loop
num = 15
fact = 1
i = 1

while i <= num:
    fact *= i
    i+= 1
    print(fact)

1
2
6
24
120
720
5040
40320
362880
3628800
39916800
479001600
6227020800
87178291200
1307674368000

# Data Types & Methods (6-9)

In [90]:
# 6. Take a string  and perform: convert to uppercase, count occurrences of ‘a’, replace spaces with -, and check if it starts with “Hello”.
string = "anil reddy"
print(string.upper())
print(string.count("a"))
print(string.replace(" ","-"))
print(string.startswith("Hello"))

ANIL REDDY
1
anil-reddy
False

In [103]:
# 7. Create a list of 6 numbers. Use append, insert, remove, pop, sort (descending) and reverse.
list1 = [1,2,3,4,5,6]
(list1.append(8))
print(list1)
(list1.insert(7,5))
print(list1)
(list1.remove(5))
print(list1)
print(list1.pop())
print(list1)
(list1.sort())
print(list1)
(list1.reverse())
print(list1)

[1, 2, 3, 4, 5, 6, 8]
[1, 2, 3, 4, 5, 6, 8, 5]
[1, 2, 3, 4, 6, 8, 5]
5
[1, 2, 3, 4, 6, 8]
[1, 2, 3, 4, 6, 8]
[8, 6, 4, 3, 2, 1]

In [115]:
# 8. Create a dictionary of 4 students (name:marks). Print only those students who scored more than 80 using items().
dist = {
    "rakhi":41,
    "babu":74,
    "ammu":89,
    "anil":96
}
print(dist.values())
for name,marks in dist.items():

    if marks > 80:
        print(name,":",marks)

dict_values([41, 74, 89, 96])
ammu : 89
anil : 96

In [119]:
# 9. Create two sets and perform union, intersection, difference. Also add and discard elements.
s1 = {1,2,3,4,5,6}
s2 = {7,8,9,10,11,12}
print(s1.union(s2))

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}

# OOP + Encapsulation (10-14)

In [122]:
#10. Create a class Student with private attribute __marks. Add getter and setter with validation (0–100).
class student:
    def __init__(self):
        self.__marks = 0
    def get_marks(self):
        return self.__marks
    def set_marks(self,marks):
        if 0 <= marks <=100:
            self.__marks = marks
        else:
            print("Enter marks between 0 and 100.")

# obj
st = student()
st.set_marks(85)
print("Marks:", st.get_marks())

Marks: 85

In [123]:
#11. Create class BankAccount with private __balance. Add deposit and withdraw methods.
#Raise custom exception if balance becomes negative.
class NegativeBalanceError(Exception):
    pass

class BankAccount:
    def __init__(self,balance):
        self.__balance = balance
    def deposit(self, amount):
        self.__balance += amount
        print("Deposited:", amount)
        print("Balance:", self.__balance)

    def withdraw(self, amount):
        if self.__balance - amount < 0:
            raise NegativeBalanceError("Insufficient Balance!")
        self.__balance -= amount
        print("Withdrawn:", amount)
        print("Balance:", self.__balance)
    def get_balance(self):
        return self.__balance


# Create object
acc = BankAccount(1000)

try:
    acc.deposit(500)
    acc.withdraw(1200)
    acc.withdraw(500)   
except NegativeBalanceError as e:
    print(e)

Deposited: 500
Balance: 1500
Withdrawn: 1200
Balance: 300
Insufficient Balance!

In [1]:
# 12. Create class Employee with class attribute company_name. Show that it is shared by all objects. Also update the class attribute.
class Employee:
    company_name = "ABC Technologies"

    def __init__(self, name):
        self.name = name

    def display(self):
        print(f"Employee: {self.name}, Company: {Employee.company_name}")


# Creating objects
emp1 = Employee("Anil")
emp2 = Employee("Ravi")

print("Before updating class attribute:")
emp1.display()
emp2.display()

# Updating the class attribute
Employee.company_name = "XYZ Solutions"

print("\nAfter updating class attribute:")
emp1.display()
emp2.display()

Before updating class attribute:
Employee: Anil, Company: ABC Technologies
Employee: Ravi, Company: ABC Technologies

After updating class attribute:
Employee: Anil, Company: XYZ Solutions
Employee: Ravi, Company: XYZ Solutions

In [2]:
# 13. Create class Product with private __price. Add getter and setter. Setter should not allow price less than 100.
class Product:
    def __init__(self, price):
        self.__price = 100  # Default value
        self.set_price(price)

    # Getter
    def get_price(self):
        return self.__price

    # Setter
    def set_price(self, price):
        if price >= 100:
            self.__price = price
        else:
            print("Price should not be less than 100.")

# Creating object
p1 = Product(500)
print("Product Price:", p1.get_price())

# Updating price with valid value
p1.set_price(750)
print("Updated Price:", p1.get_price())

# Trying to set invalid price
p1.set_price(50)
print("Final Price:", p1.get_price())

Product Price: 500
Updated Price: 750
Price should not be less than 100.
Final Price: 750

In [3]:
#14. Create class Rectangle with private length and width. Add method to calculate area and perimeter.
class Rectangle:
    def __init__(self, length, width):
        self.__length = length    # Private attribute
        self.__width = width      # Private attribute

    # Method to calculate area
    def area(self):
        return self.__length * self.__width

    # Method to calculate perimeter
    def perimeter(self):
        return 2 * (self.__length + self.__width)


# Creating an object
r1 = Rectangle(10, 5)

print("Area:", r1.area())
print("Perimeter:", r1.perimeter())

Area: 50
Perimeter: 30

# Inheritance + Abstraction + super() (15-19)

In [5]:
# 15. Create single level inheritance: Person → Student. Use super() in constructor.
class person:
    def __init__(self,name,age):
        self.name = name
        self.age = age

class Student(person):
    def __init__(self,name, age, course):
        super().__init__(name, age)   # Call parent constructor
        self.course = course

    def display(self):
        print("Name:", self.name)
        print("Age:", self.age)
        print("Course:", self.course)


# Creating object
s1 = Student("Anil", 20, "B.Tech CSE")
s1.display()

Name: Anil
Age: 20
Course: B.Tech CSE

In [6]:
# 16. Create multi-level inheritance: Person → Employee → Manager. Override a method at each level.

class Person:
    def show(self):
        print("I am a Person")

class Employee(Person):
    def show(self):
        print("I am an Employee")

class Manager(Employee):
    def show(self):
        print("I am a Manager")


# Creating objects
p = Person()
e = Employee()
m = Manager()

p.show()
e.show()
m.show()

I am a Person
I am an Employee
I am a Manager

In [7]:
# 17. Create hierarchical inheritance: Parent Animal → Dog and Cat. Override sound() method.

class Animal:
    def sound(self):
        print("Animals make sounds")

class Dog(Animal):
    def sound(self):
        print("Dog barks: Bow Bow")

class Cat(Animal):
    def sound(self):
        print("Cat meows: Meow Meow")



d = Dog()
c = Cat()

d.sound()
c.sound()

Dog barks: Bow Bow
Cat meows: Meow Meow

In [8]:
# 18. Create abstract class Shape with abstract method area(). Implement it in Circle and Square using super().
from abc import ABC, abstractmethod
import math

# Abstract class
class Shape(ABC):
    def __init__(self, value):
        self.value = value
    @abstractmethod
    def area(self):
        pass

class Circle(Shape):
    def __init__(self, radius):
        super().__init__(radius)   # Call Shape constructor

    def area(self):
        return math.pi * self.value ** 2


# Square class
class Square(Shape):
    def __init__(self, side):
        super().__init__(side)     # Call Shape constructor

    def area(self):
        return self.value ** 2


# Creating objects
c = Circle(7)
s = Square(5)

print("Circle Area:", round(c.area(), 2))
print("Square Area:", s.area())

Circle Area: 153.94
Square Area: 25

In [9]:
# 19. Create multiple inheritance with two classes Father and Mother. Create child class and resolve method conflict.
# Parent class 1
class Father:
    def show(self):
        print("This is Father's method")


# Parent class 2
class Mother:
    def show(self):
        print("This is Mother's method")


# Child class (Multiple Inheritance)
class Child(Father, Mother):
    def show(self):
        print("Resolving method conflict:")
        Father.show(self)   # Call Father's method
        Mother.show(self)   # Call Mother's method


# Creating object
c = Child()
c.show()

Resolving method conflict:
This is Father's method
This is Mother's method

# Overloading + Exception + File Handling (20-25)

In [10]:
# 20. Create a class Calculator that can add 2 or 3 numbers (method overloading using *args).
class Calculator:
   
    def add(self, *args):
        if len(args) == 2:
            return args[0] + args[1]
        elif len(args) == 3:
            return args[0] + args[1] + args[2]
        else:
            return "Please enter only 2 or 3 numbers."


# Creating object
calc = Calculator()

print("Sum of 2 numbers:", calc.add(10, 20))
print("Sum of 3 numbers:", calc.add(10, 20, 30))
print(calc.add(10))          # Invalid
print(calc.add(10, 20, 30, 40))  # Invalid

Sum of 2 numbers: 30
Sum of 3 numbers: 60
Please enter only 2 or 3 numbers.
Please enter only 2 or 3 numbers.

In [12]:
#  21. Create class Point and overload + and > operators.
class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    # Overload + operator
    def __add__(self, other):
        return Point(self.x + other.x, self.y + other.y)

    # Overload > operator
    def __gt__(self, other):
        return (self.x + self.y) > (other.x + other.y)

    def display(self):
        print(f"({self.x}, {self.y})")


# Creating objects
p1 = Point(2, 3)
p2 = Point(4, 5)

# Using + operator
p3 = p1 + p2
print("After adding points:")
p3.display()

# Using > operator
if p1 > p2:
    print("p1 is greater than p2")
else:
    print("p2 is greater than or equal to p1")

After adding points:
(6, 8)
p2 is greater than or equal to p1

In [13]:
# 22. Write a program that handles ZeroDivisionError, ValueError and IndexError using multiple except blocks.
try:
    # Input from user
    num1 = int(input("Enter first number: "))
    num2 = int(input("Enter second number: "))

    # Division
    result = num1 / num2
    print("Result:", result)

    # List access
    numbers = [10, 20, 30]
    index = int(input("Enter index (0-2): "))
    print("Element:", numbers[index])

# Handles invalid integer input
except ValueError:
    print("Error: Please enter valid integer values.")

# Handles division by zero
except ZeroDivisionError:
    print("Error: Division by zero is not allowed.")

# Handles invalid list index
except IndexError:
    print("Error: List index is out of range.")

Enter first number:  10
Enter second number:  555

Result: 0.018018018018018018

Enter index (0-2):  0

Element: 10

In [14]:
#23. Create a custom exception InvalidAgeError. Raise it if age is less than 18.

class InvalidAgeError(Exception):
    pass

try:
    age = int(input("Enter your age: "))

    if age < 18:
        raise InvalidAgeError("Age must be 18 or above.")

    print("Eligible")

except InvalidAgeError as e:
    print("Error:", e)

except ValueError:
    print("Error: Please enter a valid age.")

Enter your age:  20

Eligible

In [15]:
# 24. Write a program to read a file, count number of words, and write the count into another file.
# Read a file, count words, and write the count to another file

try:
    # Open and read the input file
    with open("input.txt", "r") as infile:
        content = infile.read()

    # Count words
    word_count = len(content.split())

    # Write the word count to another file
    with open("output.txt", "w") as outfile:
        outfile.write(f"Number of words: {word_count}")

    print("Word count written to output.txt successfully.")

except FileNotFoundError:
    print("Error: input.txt file not found.")

Error: input.txt file not found.

In [16]:
#25. Create a menu-driven program for file operations: Write, Read, Append, and Exit. Handle FileNotFoundError.
while True:
    print("\n----- File Menu -----")
    print("1. Write to File")
    print("2. Read File")
    print("3. Append to File")
    print("4. Exit")

    choice = input("Enter your choice (1-4): ")

    if choice == "1":
        data = input("Enter text to write: ")
        with open("sample.txt", "w") as file:
            file.write(data)
        print("Data written successfully.")

    elif choice == "2":
        try:
            with open("sample.txt", "r") as file:
                print("\nFile Content:")
                print(file.read())
        except FileNotFoundError:
            print("Error: File not found.")

    elif choice == "3":
        data = input("Enter text to append: ")
        with open("sample.txt", "a") as file:
            file.write("\n" + data)
        print("Data appended successfully.")

    elif choice == "4":
        print("Exiting program...")
        break

    else:
        print("Invalid choice! Please enter 1 to 4.")

----- File Menu -----
1. Write to File
2. Read File
3. Append to File
4. Exit

Enter your choice (1-4):  1
Enter text to write:  wjhdb

Data written successfully.

----- File Menu -----
1. Write to File
2. Read File
3. Append to File
4. Exit

Enter your choice (1-4):  1
Enter text to write:  sdbv

Data written successfully.

----- File Menu -----
1. Write to File
2. Read File
3. Append to File
4. Exit

Enter your choice (1-4):  4

Exiting program...

In [17]:
# 26. Create a class Student with private marks list.
"""• Setter should validate each mark (0-100)
• Overload > operator to compare two students based on average
• Raise custom exception if marks list is empty"""
# Custom Exception
class EmptyMarksError(Exception):
    pass


class Student:
    def __init__(self, marks):
        self.__marks = []
        self.set_marks(marks)

    # Setter with validation
    def set_marks(self, marks):
        if len(marks) == 0:
            raise EmptyMarksError("Marks list cannot be empty.")

        for mark in marks:
            if mark < 0 or mark > 100:
                raise ValueError("Each mark must be between 0 and 100.")

        self.__marks = marks

    # Getter
    def get_marks(self):
        return self.__marks

    # Calculate average
    def average(self):
        return sum(self.__marks) / len(self.__marks)

    # Overload > operator
    def __gt__(self, other):
        return self.average() > other.average()


# Main Program
try:
    s1 = Student([80, 90, 85])
    s2 = Student([70, 75, 80])

    print("Student 1 Average:", s1.average())
    print("Student 2 Average:", s2.average())

    if s1 > s2:
        print("Student 1 has higher average.")
    else:
        print("Student 2 has higher or equal average.")

    # Uncomment to test exceptions
    # s3 = Student([])          # EmptyMarksError
    # s4 = Student([90, 105])   # ValueError

except EmptyMarksError as e:
    print("Error:", e)

except ValueError as e:
    print("Error:", e)

Student 1 Average: 85.0
Student 2 Average: 75.0
Student 1 has higher average.

In [18]:
# 27. Write a menu-driven banking system using OOP + File Handling. Store account details in a file. Handle FileNotFoundError, ValueError, and custom exceptions.
# Menu-Driven Banking System using OOP + File Handling

# Custom Exception
class InsufficientBalanceError(Exception):
    pass


class BankAccount:
    FILE_NAME = "accounts.txt"

    def __init__(self, acc_no, name, balance=0):
        self.acc_no = acc_no
        self.name = name
        self.balance = balance

    # Save account details
    def save_account(self):
        with open(self.FILE_NAME, "a") as file:
            file.write(f"{self.acc_no},{self.name},{self.balance}\n")

    # Deposit amount
    def deposit(self, amount):
        if amount <= 0:
            raise ValueError("Deposit amount must be positive.")
        self.balance += amount
        print("Deposit Successful.")
        self.update_file()

    # Withdraw amount
    def withdraw(self, amount):
        if amount <= 0:
            raise ValueError("Withdrawal amount must be positive.")
        if amount > self.balance:
            raise InsufficientBalanceError("Insufficient Balance.")
        self.balance -= amount
        print("Withdrawal Successful.")
        self.update_file()

    # Update account in file
    def update_file(self):
        try:
            with open(self.FILE_NAME, "r") as file:
                accounts = file.readlines()

            with open(self.FILE_NAME, "w") as file:
                for acc in accounts:
                    data = acc.strip().split(",")
                    if data[0] == self.acc_no:
                        file.write(f"{self.acc_no},{self.name},{self.balance}\n")
                    else:
                        file.write(acc)

        except FileNotFoundError:
            print("Error: Account file not found.")

    # Display account
    def display(self):
        print("\nAccount Number:", self.acc_no)
        print("Name:", self.name)
        print("Balance:", self.balance)


# Search account
def search_account(acc_no):
    try:
        with open("accounts.txt", "r") as file:
            for line in file:
                data = line.strip().split(",")
                if data[0] == acc_no:
                    return BankAccount(data[0], data[1], float(data[2]))
    except FileNotFoundError:
        print("Error: Account file not found.")
    return None


# Menu
while True:
    print("\n===== BANK MENU =====")
    print("1. Create Account")
    print("2. Deposit")
    print("3. Withdraw")
    print("4. Display Account")
    print("5. Exit")

    choice = input("Enter Choice: ")

    try:
        if choice == "1":
            acc = input("Account Number: ")
            name = input("Name: ")
            balance = float(input("Initial Balance: "))
            account = BankAccount(acc, name, balance)
            account.save_account()
            print("Account Created Successfully.")

        elif choice == "2":
            acc = input("Account Number: ")
            account = search_account(acc)
            if account:
                amount = float(input("Deposit Amount: "))
                account.deposit(amount)
            else:
                print("Account Not Found.")

        elif choice == "3":
            acc = input("Account Number: ")
            account = search_account(acc)
            if account:
                amount = float(input("Withdraw Amount: "))
                account.withdraw(amount)
            else:
                print("Account Not Found.")

        elif choice == "4":
            acc = input("Account Number: ")
            account = search_account(acc)
            if account:
                account.display()
            else:
                print("Account Not Found.")

        elif choice == "5":
            print("Thank You!")
            break

        else:
            print("Invalid Choice.")

    except ValueError as e:
        print("ValueError:", e)

    except InsufficientBalanceError as e:
        print("Error:", e)

    except FileNotFoundError:
        print("Error: File not found.")

===== BANK MENU =====
1. Create Account
2. Deposit
3. Withdraw
4. Display Account
5. Exit

Enter Choice:  5

Thank You!

In [20]:
# 28. Using dictionary + exception handling, create a student management system that
"""can:
• Add student
• Update marks
• Delete student
• Display all Raise custom exception if student not found."""
# Custom Exception
class StudentNotFoundError(Exception):
    pass


# Dictionary to store student details
students = {}

while True:
    print("\n===== STUDENT MANAGEMENT SYSTEM =====")
    print("1. Add Student")
    print("2. Update Marks")
    print("3. Delete Student")
    print("4. Display All Students")
    print("5. Exit")

    choice = input("Enter your choice (1-5): ")

    try:
        if choice == "1":
            name = input("Enter student name: ")
            marks = int(input("Enter marks: "))

            if marks < 0 or marks > 100:
                raise ValueError("Marks must be between 0 and 100.")

            students[name] = marks
            print("Student added successfully.")

        elif choice == "2":
            name = input("Enter student name to update: ")

            if name not in students:
                raise StudentNotFoundError("Student not found.")

            marks = int(input("Enter new marks: "))

            if marks < 0 or marks > 100:
                raise ValueError("Marks must be between 0 and 100.")

            students[name] = marks
            print("Marks updated successfully.")

        elif choice == "3":
            name = input("Enter student name to delete: ")

            if name not in students:
                raise StudentNotFoundError("Student not found.")

            del students[name]
            print("Student deleted successfully.")

        elif choice == "4":
            if not students:
                print("No student records found.")
            else:
                print("\nStudent Records")
                for name, marks in students.items():
                    print(f"{name} : {marks}")

        elif choice == "5":
            print("Exiting program...")
            break

        else:
            print("Invalid choice.")

    except ValueError as e:
        print("ValueError:", e)

    except StudentNotFoundError as e:
        print("Error:", e)

===== STUDENT MANAGEMENT SYSTEM =====
1. Add Student
2. Update Marks
3. Delete Student
4. Display All Students
5. Exit

Enter your choice (1-5):  5

Exiting program...

In [21]:
# 29. Create a class Employee with private salary.
"""• Setter should not allow more than 15% increase at once
• Keep history of all salary changes
• Add static method to calculate tax
• Overload > operator to compare employees by salary"""
class Employee:
    def __init__(self, name, salary):
        self.name = name
        self.__salary = salary
        self.__history = [salary]   # Store salary history

    # Getter
    def get_salary(self):
        return self.__salary

    # Setter (maximum 15% increase allowed)
    def set_salary(self, new_salary):
        if new_salary > self.__salary * 1.15:
            print("Salary increase cannot exceed 15% at a time.")
        else:
            self.__salary = new_salary
            self.__history.append(new_salary)
            print("Salary updated successfully.")

    # Display salary history
    def show_history(self):
        print("Salary History:", self.__history)

    # Static method to calculate tax (10%)
    @staticmethod
    def calculate_tax(salary):
        return salary * 0.10

    # Overload > operator
    def __gt__(self, other):
        return self.__salary > other.__salary


# Creating objects
e1 = Employee("Anil", 50000)
e2 = Employee("Ravi", 60000)

# Valid salary update
e1.set_salary(55000)

# Invalid salary update (more than 15%)
e1.set_salary(70000)

print("\nCurrent Salary:", e1.get_salary())
e1.show_history()

print("Tax on Salary:", Employee.calculate_tax(e1.get_salary()))

# Compare salaries
if e1 > e2:
    print("Anil has a higher salary.")
else:
    print("Ravi has a higher or equal salary.")

Salary updated successfully.
Salary increase cannot exceed 15% at a time.

Current Salary: 55000
Salary History: [50000, 55000]
Tax on Salary: 5500.0
Ravi has a higher or equal salary.

In [22]:
# 30. Design a complete system combining:
"""• Abstract class Vehicle
• Multiple inheritance (Electric + Fuel)
• Operator overloading (compare by speed)
• Private attributes + getter/setter
• Custom exceptions
• File handling to save vehicle details
• Duck Typing for start() method"""
from abc import ABC, abstractmethod

# ---------------- Custom Exception ----------------
class InvalidSpeedError(Exception):
    pass


# ---------------- Abstract Class ----------------
class Vehicle(ABC):
    def __init__(self, name, speed):
        self.__speed = 0
        self.name = name
        self.set_speed(speed)

    # Getter
    def get_speed(self):
        return self.__speed

    # Setter
    def set_speed(self, speed):
        if speed < 0:
            raise InvalidSpeedError("Speed cannot be negative.")
        self.__speed = speed

    @abstractmethod
    def vehicle_type(self):
        pass

    # Operator Overloading (>)
    def __gt__(self, other):
        return self.__speed > other.__speed


# ---------------- Parent Classes ----------------
class Electric:
    def charge(self):
        print("Charging electric vehicle...")


class Fuel:
    def fill_fuel(self):
        print("Filling fuel tank...")


# ---------------- Child Class (Multiple Inheritance) ----------------
class HybridVehicle(Vehicle, Electric, Fuel):
    def __init__(self, name, speed):
        super().__init__(name, speed)

    def vehicle_type(self):
        print("Hybrid Vehicle")

    # Duck Typing Method
    def start(self):
        print(self.name, "started.")


# ---------------- File Handling ----------------
def save_vehicle(vehicle):
    with open("vehicles.txt", "a") as file:
        file.write(f"{vehicle.name},{vehicle.get_speed()}\n")


# ---------------- Duck Typing Function ----------------
def start_vehicle(obj):
    obj.start()      # Any object having start() method works


# ---------------- Main Program ----------------
try:
    v1 = HybridVehicle("Tesla Hybrid", 180)
    v2 = HybridVehicle("Toyota Hybrid", 150)

    v1.vehicle_type()
    v1.charge()
    v1.fill_fuel()

    # Operator Overloading
    if v1 > v2:
        print(v1.name, "is faster than", v2.name)
    else:
        print(v2.name, "is faster")

    # Duck Typing
    start_vehicle(v1)

    # Save to File
    save_vehicle(v1)
    save_vehicle(v2)

    print("Vehicle details saved successfully.")

except InvalidSpeedError as e:
    print("Error:", e)

except FileNotFoundError:
    print("File not found.")

except Exception as e:
    print("Unexpected Error:", e)

Hybrid Vehicle
Charging electric vehicle...
Filling fuel tank...
Tesla Hybrid is faster than Toyota Hybrid
Tesla Hybrid started.
Vehicle details saved successfully.